# 01 - First Look: Sampling the Raw Data

**Stage 1 of the project.**

This notebook is the first thing anyone opening this repository should run.
Its only job is to answer one question: *"what condition is the raw data
actually in?"* -- before we touch a single value. We start with a quick,
visual peek at rows that are obviously off, then follow up with a
systematic pass over every table.

### Why this step exists
In a real factory, data does not arrive clean. It comes out of MES
(Manufacturing Execution System) exports, shift-handover spreadsheets, and
paper travelers typed up after the fact. Different operators type the same
thing in different ways, fields get left blank, and copy-paste mistakes
duplicate rows. Before any KPI (OEE, Cp/Cpk, MTBF...) can be trusted, we
have to know exactly how dirty the input is -- otherwise a wrong number in
the data becomes a wrong number in the dashboard, silently.

We do **not** fix anything in this notebook -- that is Stage 3
(`02_data_cleaning_production.ipynb`). Keeping "look" and "fix" in
separate notebooks is a deliberate habit: it forces you to write down
every problem you found *before* you start solving them, so nothing gets
fixed by accident without being noticed and explained.

In [1]:
import pandas as pd
pd.set_option('display.max_columns', 50)
pd.set_option('display.width', 160)

RAW = '../../datasets/raw'
DIM = '../../datasets/dim'

## 0. A first peek: what does "bad data" actually look like here?

Before running anything systematic, it's worth just *looking* at a
handful of rows that are visibly off -- this is the fastest way to
build intuition for what Stage 3 will need to handle.

In [2]:
prod_peek = pd.read_csv(f'{RAW}/fact_production_raw.csv', encoding='utf-8-sig')
downtime_peek = pd.read_csv(f'{RAW}/fact_downtime_raw.csv', encoding='utf-8-sig')

print("-- Inconsistent category casing (same process, typed differently) --")
display(prod_peek[prod_peek['Process'].isin(['injection molding', 'INJECTION MOLDING', '  Injection Molding  '])].head(6))

print("-- A quantity that should never be negative --")
display(prod_peek[prod_peek['RejectedQty'] < 0].head(6))

print("-- Fully duplicated rows --")
display(prod_peek[prod_peek.duplicated(keep=False)].sort_values('WorkOrder').head(6))

print("-- Placeholder nulls hiding in a text field ('-', '/', a lone space) --")
display(downtime_peek[downtime_peek['MaintenanceTechnician'].isin(['-', '--', '/', '//', ' ', '  '])].head(6))

-- Inconsistent category casing (same process, typed differently) --

,Date,Process,MachineId,ToolId,WorkOrder,ProductId,ProductBatch,StartTime,EndTime,PlannedQty,ProducedQty,RejectedQty,OperatorId
5,2026-01-02,injection molding,IM-005,M-INJ-008,WO-4269,TF-008-PP-PCR-28410,26002002700,11:08:00,18:33:00,5684,5684,185,OP-INJ-003
12,2026-04-15,Injection Molding,IM-002,RS-HF-002,WO-2895,TR-002-HDPE-24410,26105008960,00:19:00,11:12:00,5306,5324,168,OP-INJ-002
24,2026-05-21,Injection Molding,IM-001,M-INJ-001,WO-2440,TR-001-PP-24410,26141004410,07:59:00,23:12:00,18053,18053,240,OP-INJ-003
32,2026-02-16,Injection Molding,IM-006,M-INJ-006,WO-4846,TF-006-HDPE-24415,26047008470,22:13:00,11:25:00,5259,5402,312,OP-INJ-001
36,2026-04-27,injection molding,IM-005,M-INJ-005,WO-4432,TF-005-PP-24410,26117004330,21:46:00,03:38:00,4638,4738,88,OP-INJ-001
41,2025-10-21,injection molding,IM-002,M-INJ-002,WO-2646,TR-002-PETG-24410,25294006470,00:56:00,14:06:00,9653,9934,488,OP-INJ-002

-- A quantity that should never be negative --

,Date,Process,MachineId,ToolId,WorkOrder,ProductId,ProductBatch,StartTime,EndTime,PlannedQty,ProducedQty,RejectedQty,OperatorId
15,2025-11-28,blow molding,ISBM-006,M-SOP-014,WO-7792,FR-014-PP-PCR-500,25332007930,19:04:00,03:23:00,4738,4886,-107,OP-SOP-002
388,2026-03-31,Hot Foil Stamping,HF-001,RS-HF-002,WO-1356,FR-015-PETG-500,26090003570,10:27:00,05:50:00,12074,12198,-16,OP-HF-001
499,2026-01-06,INJECTION MOLDING,IM-002,M-INJ-002,WO-2758,TR-002-HDPE-24410,26006007590,08:47:00,15:16:00,4900,4942,-153,OP-INJ-001
682,2026-02-10,Injection Molding,IM-006,M-INJ-009,WO-4836,TF-009-HDPE-28415,26041008370,15:08:00,07:22:00,9381,9487,-580,OP-INJ-002
1030,2025-11-13,blow molding,ISBM-008,M-SOP-019,WO-8771,FR-019-rPET-600,25317007720,11:14:00,18:49:00,4206,4307,-76,OP-SOP-001
1145,2025-08-06,Injection Molding,IM-006,M-INJ-009,WO-4573,TF-009-HDPE-28415,25218005740,19:44:00,07:00:00,6625,6782,-391,OP-INJ-003

-- Fully duplicated rows --

,Date,Process,MachineId,ToolId,WorkOrder,ProductId,ProductBatch,StartTime,EndTime,PlannedQty,ProducedQty,RejectedQty,OperatorId
5032,2026-01-15,INJECTION MOLDING,IM-001,M-INJ-001,WO-2270,TR-001-HDPE-24410,26015002710,19:39:00,07:21:00,13993,14143,146,AUX-INJ-001
2768,2026-01-15,INJECTION MOLDING,IM-001,M-INJ-001,WO-2270,TR-001-HDPE-24410,26015002710,19:39:00,07:21:00,13993,14143,146,AUX-INJ-001
4236,2026-03-06,Injection Molding,IM-001,M-INJ-001,WO-2339,TR-001-PP-24410,26065003400,17:47:00,01:06:00,8643,8643,237,OP-INJ-002
2904,2026-03-06,Injection Molding,IM-001,M-INJ-001,WO-2339,TR-001-PP-24410,26065003400,17:47:00,01:06:00,8643,8643,237,OP-INJ-002
5667,2026-04-01,Injection Molding,IM-001,M-INJ-001,WO-2375,TR-001-PP-24410,26091003760,07:28:00,19:17:00,13084,13084,326,AUX-INJ-001
6446,2026-04-01,Injection Molding,IM-001,M-INJ-001,WO-2375,TR-001-PP-24410,26091003760,07:28:00,19:17:00,13084,13084,326,AUX-INJ-001

-- Placeholder nulls hiding in a text field ('-', '/', a lone space) --

,Date,Process,MachineId,Shift,StoppageStartTime,StoppageEndTime,PlannedStoppage,StoppageReason,MaintenanceTeam,MaintenanceTechnician
41,2025-09-19,Blow Molding,ISBM-002,Shift 2,20:28:00,21:34:00,Yes,Planned Preventive Maintenance,Mechanical,--
219,2026-04-23,Blow Molding,ISBM-005,Shift 2,20:42:00,22:11:00,No,Mechanical Failure (Breakage/Jam),Mechanical,
655,2025-08-20,Injection Molding,IM-004,Shift 3,02:00:00,03:20:00,Yes,"Meal Break (Shift 3 - no relief crew, 10min sh...",N/A (Operations),--
698,2026-01-01,blow molding,ISBM-004,shift 1,11:17:00,11:46:00,No,Quality Adjustment (Rejects),Mechanical,
1001,2025-11-04,Blow Molding,ISBM-006,Shift 1,12:19:00,13:06:00,Yes,Mold Change / Setup,Mechanical,--
1067,2025-08-13,Blow Molding,ISBM-006,SHIFT 3,04:51:00,05:29:00,No,Utilities Shortage (Compressed Air),Utilities,/

That's the flavor of it. Now the systematic pass: for every raw table in
`datasets/raw/` and `datasets/dim/` we run the classic first-look trio:

| Function | What it tells us |
|---|---|
| `df.head(30)` | What the data actually looks like, row by row |
| `df.info()` | Column names, data types, and non-null counts in one shot |
| `df.isna().sum()` | Exactly how many missing values are in each column |

## 1. Fact tables (production, downtime, material consumption, plan)

These four tables are the operational backbone of the project: every
work order, every machine stoppage, and every raw-material lot consumed
on the shop floor.

In [3]:
fact_files = {
    'fact_production_plan_raw': f'{RAW}/fact_production_plan_raw.csv',
    'fact_production_raw': f'{RAW}/fact_production_raw.csv',
    'fact_downtime_raw': f'{RAW}/fact_downtime_raw.csv',
    'fact_material_consumption_raw': f'{RAW}/fact_material_consumption_raw.csv',
}

raw_tables = {name: pd.read_csv(path, encoding='utf-8-sig') for name, path in fact_files.items()}
for name, df in raw_tables.items():
    print(f"{name}: {df.shape[0]:,} rows x {df.shape[1]} columns")

fact_production_plan_raw: 9,128 rows x 10 columns
fact_production_raw: 9,137 rows x 13 columns
fact_downtime_raw: 21,874 rows x 10 columns
fact_material_consumption_raw: 23,504 rows x 10 columns

In [4]:
# head(30) for every fact table -- what does the data actually look like?
for name, df in raw_tables.items():
    print(f"\n{'='*100}\n{name} -- first 30 rows\n{'='*100}")
    display(df.head(30))

====================================================================================================
fact_production_plan_raw -- first 30 rows
====================================================================================================

          Date                Process MachineId                ToolId WorkOrder  PlannedQty StartTime   EndTime  PlannedHours            ProductId
0   2025-09-09         Blow Molding    ISBM-002             M-SOP-008   WO-5651        8830  18:23:00  09:25:00         15.03  FR-008-HDPE-PCR-350
1   2025-08-12      Injection Molding    IM-005             M-INJ-008   WO-4074       16335  22:46:00  20:27:00         21.68    TF-008-HDPE-28410
2   2025-10-08           BLOW MOLDING  ISBM-003             M-SOP-025   WO-6199        4841  13:14:00  06:26:00         17.19      FR-025-PET-1000
3   2026-01-05           Blow Molding  ISBM-005             M-SOP-010   WO-7328       10067  21:51:00  15:15:00         17.41       FR-010-PET-400
4   2026-04-09    Injection Molding      IM-003             M-INJ-003   WO-3382       19922  10:31:00  00:05:00         13.57      TR-003-PP-24415
5   2025-11-04      Injection Molding    IM-001             M-INJ-001   WO-2170        7549  17:08:00  00:02:00          6.89  TR-001-PP-PCR-24410
6   2025-12-26           blow molding  ISBM-005             M-SOP-023   WO-7316        4061  13:40:00  03:37:00         13.94     FR-023-rPET-1000
7   2026-03-27           Blow Molding  ISBM-007             M-SOP-015   WO-8456        8926  02:33:00  23:34:00         21.02  FR-015-HDPE-PCR-500
8   2025-09-20         Blow Molding    ISBM-006             M-SOP-014   WO-7693        2899  00:45:00  06:00:00          5.25      FR-014-rPET-500
9   2025-12-17           blow molding  ISBM-006             M-SOP-011   WO-7815        8745  12:20:00  03:32:00         15.21       FR-011-PET-400
10  2026-06-22           Blow Molding  ISBM-002             M-SOP-002   WO-6051        4601  06:00:00  13:44:00          7.74  FR-002-HDPE-PCR-300
11  2025-11-18         Blow Molding    ISBM-005             M-SOP-013   WO-7260        8082  19:47:00  09:43:00         13.94       FR-013-PET-500
12  2026-04-27        SCREEN PRINTING    SS-002  SK-FR-013-PET-500-2C   WO-9995        9918  18:43:00  06:36:00         11.89       FR-013-PET-500
13  2025-09-03      Injection Molding    IM-001             M-INJ-001   WO-2086       14942  19:28:00  09:04:00         13.60      TR-001-PP-24410
14  2025-09-09    Hot Foil Stamping      HF-002             RS-HF-002   WO-1580        4940  18:03:00  02:28:00          8.42       FR-008-PET-350
15  2026-07-01      injection molding    IM-006             M-INJ-009   WO-5037        5083  07:28:00  16:37:00          9.15      TF-009-PP-28415
16  2026-03-03        Screen Printing    SS-001   SK-FR-020-PP-750-2C   WO-9412        5126  14:09:00  19:38:00          5.48        FR-020-PP-750
17  2026-03-26      INJECTION MOLDING    IM-006             M-INJ-006   WO-4904        4577  15:00:00  03:03:00         12.06    TF-006-HDPE-24415
18  2025-12-23      INJECTION MOLDING    IM-002             RS-HF-002   WO-2736        5475  17:25:00  05:08:00         11.71    TR-002-HDPE-24410
19  2025-08-29           Blow Molding  ISBM-003             M-SOP-009   WO-6147        4322  08:35:00  18:23:00          9.80      FR-009-rPET-350
20  2025-12-23           Blow Molding  ISBM-003             M-SOP-006   WO-6312        5176  14:59:00  03:39:00         12.66      FR-006-rPET-330
21  2026-05-09           Blow Molding  ISBM-001             M-SOP-007   WO-5476        6505  10:43:00  22:00:00         11.28       FR-007-PVC-350
22  2025-12-04           Blow Molding  ISBM-004             M-SOP-012   WO-6783       12545  05:24:00  02:22:00         20.97       FR-012-PET-400
23  2025-07-21           Blow Molding  ISBM-002             M-SOP-008   WO-5581        6123  12:08:00  22:59:00         10.85      FR-008-rPET-350
24  2025-10-10    Injection Molding      IM-004             M-INJ-007   WO-3649       10007  01:03:00  17:48:00         16.75  TF-007-PP-PCR-28410
25  2026-04-07           blow molding  ISBM-004             M-SOP-004   WO-6949        6559  18:19:00  06:00:00         11.68      FR-004-rPET-330
26  2025-08-05      Hot Foil Stamping    HF-002             RS-HF-001   WO-1528        5585  20:07:00  06:18:00         10.19      FR-022-PVC-1000
27  2026-06-30    Injection Molding      IM-003             M-INJ-003   WO-3502       21766  19:20:00  09:31:00         14.18  TR-003-PP-PCR-24415
28  2025-09-19        SCREEN PRINTING    SS-001  SK-FR-013-PVC-500-2C   WO-9186       13370  04:20:00  19:55:00         15.58       FR-013-PVC-500
29  2025-10-14           BLOW MOLDING  ISBM-003             M-SOP-009   WO-6206        6248  04:30:00  18:41:00         14.19      FR-009-PETG-350

====================================================================================================
fact_production_raw -- first 30 rows
====================================================================================================

,Date,Process,MachineId,ToolId,WorkOrder,ProductId,ProductBatch,StartTime,EndTime,PlannedQty,ProducedQty,RejectedQty,OperatorId
0,2025-12-04,Hot Foil Stamping,HF-002,RS-HF-001,WO-1703,FR-008-LDPE-350,25338007040,13:39:00,19:40:00,3417,3511,6,OP-HF-002
1,2026-05-19,Blow Molding,ISBM-007,M-SOP-020,WO-8533,FR-020-rPET-750,26139005340,21:28:00,12:53:00,6341,6442,168,OP-SOP-001
2,2025-08-12,Blow Molding,ISBM-003,M-SOP-006,WO-6123,FR-006-rPET-330,25224001240,01:09:00,17:06:00,6970,7202,130,OP-SOP-001
3,2025-07-30,Blow Molding,ISBM-002,M-SOP-008,WO-5594,FR-008-PETG-350,25211005950,01:22:00,17:26:00,9042,9042,281,OP-SOP-001
4,2025-12-01,Injection Molding,IM-002,M-INJ-002,WO-2703,TR-002-PETG-24410,25335007040,06:00:00,23:07:00,13179,13421,378,AUX-INJ-001
5,2026-01-02,injection molding,IM-005,M-INJ-008,WO-4269,TF-008-PP-PCR-28410,26002002700,11:08:00,18:33:00,5684,5684,185,OP-INJ-003
6,2025-09-18,Blow Molding,ISBM-006,M-SOP-018,WO-7691,FR-018-PP-600,25261006920,09:42:00,07:38:00,12390,12390,255,---
7,2025-09-08,Blow Molding,ISBM-003,M-SOP-009,WO-6158,FR-009-HDPE-PCR-350,25251001590,06:29:00,22:31:00,7101,7199,120,NaN
8,2026-01-28,Blow Molding,ISBM-004,M-SOP-004,WO-6861,FR-004-rPET-330,26028008620,06:04:00,19:38:00,7740,7867,112,OP-SOP-004
9,2026-04-10,Blow Molding,ISBM-004,M-SOP-029,WO-6954,FR-029-MDPE-5000,26100009550,21:04:00,16:16:00,1735,1760,194,OP-SOP-001
10,2026-03-28,Injection Molding,IM-002,M-INJ-002,WO-2870,TR-002-PP-PCR-24410,26087008710,03:03:00,10:07:00,5456,5564,258,OP-INJ-003
11,2025-10-10,Screen Printing,SS-002,SK-FR-019-rPET-600-2C,WO-9719,FR-019-rPET-600,25283007200,02:07:00,23:34:00,17708,17927,85,OP-SK-002
12,2026-04-15,Injection Molding,IM-002,RS-HF-002,WO-2895,TR-002-HDPE-24410,26105008960,00:19:00,11:12:00,5306,5324,168,OP-INJ-002
13,2025-11-17,Hot Foil Stamping,HF-001,RS-HF-002,WO-1164,FR-008-rPET-350,25321001650,06:00:00,11:11:00,3369,3369,6,OP-HF-002
14,2025-09-30,Injection Molding,IM-005,M-INJ-008,WO-4138,TF-008-HDPE-28410,25273001390,04:25:00,22:12:00,13310,13310,499,OP-INJ-003
15,2025-11-28,blow molding,ISBM-006,M-SOP-014,WO-7792,FR-014-PP-PCR-500,25332007930,19:04:00,03:23:00,4738,4886,-107,OP-SOP-002
16,2025-08-11,Blow Molding,ISBM-007,M-SOP-017,WO-8142,FR-017-PP-PCR-600,25223001430,22:51:00,05:50:00,3956,4039,90,OP-SOP-001
17,2025-09-17,Injection Molding,IM-003,M-INJ-003,WO-3101,TR-003-PETG-24415,25260001020,15:10:00,21:45:00,9584,9724,236,OP-INJ-001
18,2025-10-22,Blow Molding,ISBM-006,M-SOP-014,WO-7737,FR-014-PP-PCR-500,25295007380,05:04:00,20:25:00,8343,8605,165,OP-SOP-001
19,2026-03-31,Injection Molding,IM-003,M-INJ-003,WO-3369,TR-003-PP-24415,26090003700,07:10:00,13:32:00,9848,9916,204,AUX-INJ-001
20,2026-02-18,Blow Molding,ISBM-008,M-SOP-022,WO-8899,FR-022-HDPE-1000,26049009000,13:23:00,20:33:00,2986,3012,104,OP-SOP-002
21,2025-10-10,Blow Molding,ISBM-008,M-SOP-022,WO-8723,FR-022-HDPE-1000,25283007240,16:46:00,06:06:00,5554,5554,95,OP-SOP-003
22,2026-07-16,BLOW MOLDING,ISBM-006,M-SOP-018,WO-8106,FR-018-rPET-600,26197001070,13:05:00,21:45:00,5191,5237,78,OP-SOP-003
23,2026-01-20,Injection Molding,IM-006,M-INJ-009,WO-4808,TF-009-PP-PCR-28415,26020008090,16:48:00,06:05:00,7380,7617,264,OP-INJ-002
24,2026-05-21,Injection Molding,IM-001,M-INJ-001,WO-2440,TR-001-PP-24410,26141004410,07:59:00,23:12:00,18053,18053,240,OP-INJ-003
25,2026-05-07,Blow Molding,ISBM-007,M-SOP-015,WO-8514,FR-015-HDPE-PCR-500,26127005150,15:21:00,01:13:00,4275,4406,176,OP-SOP-003
26,2026-06-24,Blow Molding,ISBM-003,M-SOP-009,WO-6563,FR-009-PET-350,26175005640,06:49:00,15:16:00,3690,3803,90,OP-SOP-001
27,2025-11-25,BLOW MOLDING,ISBM-007,M-SOP-020,WO-8292,FR-020-PP-PCR-750,25329002930,17:26:00,04:52:00,4996,5084,180,OP-SOP-004
28,2026-02-24,Screen Printing,SS-002,SK-FR-014-HDPE-500-2C,WO-9908,FR-014-HDPE-500,26055009090,05:39:00,11:43:00,5239,5336,15,OP-SK-002
29,2025-12-26,Hot Foil Stamping,HF-002,RS-HF-002,WO-1733,FR-018-HDPE-PCR-600,25360007340,21:49:00,03:55:00,3331,3397,8,OP-HF-001

====================================================================================================
fact_downtime_raw -- first 30 rows
====================================================================================================

,Date,Process,MachineId,Shift,StoppageStartTime,StoppageEndTime,PlannedStoppage,StoppageReason,MaintenanceTeam,MaintenanceTechnician
0,2026-03-02,INJECTION MOLDING,IM-003,Shift 3,22:11:00,22:27:00,No,Raw Material Shortage,N/A (Operations),N/A (Operador de linha)
1,2025-07-25,Screen Printing,SS-001,shift 1,10:56:00,11:31:00,No,Mechanical Failure (Roller/Squeegee),Mechanical,Sandra Reis
2,2026-01-12,Injection Molding,IM-003,Shift 1,07:10:00,07:31:00,No,Operator Unavailable,N/A (Operations),N/A (Operador de linha)
3,2025-07-21,Blow Molding,ISBM-007,Shift 2,20:44:00,21:01:00,No,Quality Adjustment (Rejects),Mechanical,José Pinto
4,2025-11-21,injection molding,IM-005,Shift 3,04:23:00,04:55:00,No,Quality Adjustment (Rejects),Mechanical,José Pinto
5,2025-07-28,Screen Printing,SS-002,SHIFT 1,11:41:00,11:52:00,No,Color Registration Adjustment,Mechanical,Sandra Reis
6,2025-08-04,Injection Molding,IM-004,Shift 3,02:00:00,03:20:00,Yes,"Meal Break (Shift 3 - no relief crew, 10min sh...",N/A (Operations),N/A (Operador de linha)
7,2026-05-26,Blow Molding,ISBM-007,shift 3,22:44:00,23:08:00,No,Utilities Shortage (Compressed Air),Utilities,Sandra Reis
8,2025-09-01,Hot Foil Stamping,HF-001,Shift 1,09:35:00,11:04:00,Yes,Planned Preventive Maintenance,Mechanical,Sandra Reis
9,2025-10-31,BLOW MOLDING,ISBM-007,Shift 1,10:25:00,10:44:00,No,Utilities Shortage (Compressed Air),Utilities,Sandra Reis
10,2026-04-16,Hot Foil Stamping,HF-001,SHIFT 1,11:31:00,11:50:00,No,Hot Foil Ribbon Shortage,N/A (Operations),N/A (Operador de linha)
11,2026-04-25,blow molding,ISBM-001,Shift 1,09:14:00,09:58:00,No,Electrical/Control Failure,Electrical,Vitor Sousa
12,2026-02-20,injection molding,IM-005,Shift 2,17:00:00,17:22:00,No,Electrical/Control Failure,Electrical,Vitor Sousa
13,2025-09-03,Screen Printing,SS-002,SHIFT 2,19:30:00,19:45:00,No,Ink/Colorant Shortage,N/A (Operations),N/A (Operador de linha)
14,2026-02-11,Injection Molding,IM-003,Shift 3,02:00:00,03:20:00,Yes,"Meal Break (Shift 3 - no relief crew, 10min sh...",N/A (Operations),N/A (Operador de linha)
15,2026-01-15,Blow Molding,ISBM-003,Shift 2,19:01:00,20:20:00,No,Mechanical Failure (Breakage/Jam),Mechanical,Hugo Marques
16,2025-09-08,injection molding,IM-001,Shift 2,14:59:00,15:35:00,No,Raw Material Shortage,N/A (Operations),N/A (Operador de linha)
17,2026-06-09,Blow Molding,ISBM-005,Shift 1,12:41:00,13:10:00,Yes,Planned Preventive Maintenance,Mechanical,Sandra Reis
18,2026-04-01,Injection Molding,IM-003,shift 3,03:54:00,04:57:00,Yes,Mold Change / Setup,Mechanical,José Pinto
19,2026-03-26,Blow Molding,ISBM-003,Shift 3,02:00:00,03:20:00,Yes,"Meal Break (Shift 3 - no relief crew, 10min sh...",N/A (Operations),N/A (Operador de linha)
20,2025-08-22,Screen Printing,SS-002,Shift 3,02:00:00,03:20:00,Yes,"Meal Break (Shift 3 - no relief crew, 10min sh...",N/A (Operations),N/A (Operador de linha)
21,2025-11-25,BLOW MOLDING,ISBM-007,Shift 3,02:00:00,03:20:00,Yes,"Meal Break (Shift 3 - no relief crew, 10min sh...",N/A (Operations),N/A (Operador de linha)
22,2025-10-24,Injection Molding,IM-003,SHIFT 3,05:02:00,05:26:00,No,Raw Material Shortage,N/A (Operations),N/A (Operador de linha)
23,2025-10-23,Blow Molding,ISBM-007,Shift 3,02:00:00,03:20:00,Yes,"Meal Break (Shift 3 - no relief crew, 10min sh...",N/A (Operations),N/A (Operador de linha)
24,2026-04-01,INJECTION MOLDING,IM-001,Shift 3,02:00:00,03:20:00,Yes,"Meal Break (Shift 3 - no relief crew, 10min sh...",N/A (Operations),N/A (Operador de linha)
25,2025-08-22,Hot Foil Stamping,HF-001,Shift 3,02:00:00,03:20:00,Yes,"Meal Break (Shift 3 - no relief crew, 10min sh...",N/A (Operations),N/A (Operador de linha)
26,2026-05-01,INJECTION MOLDING,IM-002,Shift 1,09:46:00,10:03:00,No,Quality Adjustment (Rejects),Mechanical,José Pinto
27,2026-06-17,Blow Molding,ISBM-003,Shift 3,02:00:00,03:20:00,Yes,"Meal Break (Shift 3 - no relief crew, 10min sh...",N/A (Operations),N/A (Operador de linha)
28,2026-07-02,Blow Molding,ISBM-002,Shift 1,07:48:00,09:01:00,Yes,Planned Preventive Maintenance,Mechanical,Patrícia Lima
29,2025-08-05,INJECTION MOLDING,IM-004,SHIFT 1,10:22:00,11:47:00,Yes,Planned Preventive Maintenance,Mechanical,Sandra Reis

====================================================================================================
fact_material_consumption_raw -- first 30 rows
====================================================================================================

    RecordSeq        Date                Process MachineId        Shift WorkOrder MaterialId       MaterialLot  StartWeightKg  EndWeightKg
0       14577  2026-03-02      Hot Foil Stamping    HF-001      Shift 1   WO-1314    COR-001   COL-COR-001-107          59.11        34.24
1        4737  2025-09-30      INJECTION MOLDING    IM-003      SHIFT 3   WO-3119    COR-007   COL-COR-007-605         390.89       223.88
2       12421  2026-01-27      Screen Printing      SS-001    Shift 3     WO-9360    COR-003  COL-COR-003-2297         373.20       275.14
3        7066  2025-11-05           Blow Molding  ISBM-003      Shift 1   WO-6239    COR-008  COL-COR-008-3402          12.73        10.47
4       21517  2026-06-17         Blow Molding    ISBM-005      Shift 3   WO-7554    COR-005  COL-COR-005-1833          40.99        20.79
5        3614  2025-09-12      Injection Molding    IM-005      Shift 3   WO-4116    COR-003   COL-COR-003-680         231.61       162.45
6       23038  2026-07-10           BLOW MOLDING  ISBM-001      Shift 2   WO-5568    COR-003  COL-COR-003-1412          19.94        10.42
7       10793  2026-01-01           Blow Molding  ISBM-008      Shift 3   WO-8833    COR-006  COL-COR-006-1286          46.97        27.57
8        4892  2025-10-02      Hot Foil Stamping    HF-002      SHIFT 3   WO-1611    COR-001   COL-COR-001-190          23.61        18.64
9       17091  2026-04-09         Blow Molding    ISBM-002      Shift 3   WO-5947    COR-008  COL-COR-008-2946          37.62        17.55
10      22758  2026-07-07      injection molding    IM-001      Shift 1   WO-2504    COR-001   COL-COR-001-586         105.21        72.03
11       9374  2025-12-10           Blow Molding  ISBM-005      SHIFT 2   WO-7291    COR-002   COL-COR-002-748          10.64         8.41
12      10241  2025-12-24      INJECTION MOLDING    IM-004      Shift 3   WO-3755    COR-008  COL-COR-008-2021         281.77       165.74
13      23183  2026-07-14      Injection Molding    IM-002      Shift 2   WO-3011    COR-008  COL-COR-008-1661         373.54       284.13
14       3812  2025-09-16      Hot Foil Stamping    HF-002      SHIFT 1   WO-1589    COR-008   COL-COR-008-705          13.65         7.21
15      10139  2025-12-23      Injection Molding    IM-001      Shift 1   WO-2233    COR-007   COL-COR-007-366         150.21        69.09
16      13318  2026-02-10           blow molding  ISBM-006      Shift 1   WO-7889    COR-008  COL-COR-008-5384          44.59        22.78
17      15074  2026-03-10    Hot Foil Stamping      HF-001    Shift 1     WO-1326    COR-008   COL-COR-008-373          40.26        21.98
18      17309  2026-04-13      Injection Molding    IM-005      shift 2   WO-4413    COR-004  COL-COR-004-1370         199.60       115.96
19      23225  2026-07-14           Blow Molding  ISBM-005      Shift 2   WO-7595    COR-002   COL-COR-002-840          21.25        17.04
20       1313  2025-08-07      INJECTION MOLDING    IM-005      SHIFT 3   WO-4066    COR-004  COL-COR-004-1010         164.76       129.43
21       9561  2025-12-13      hot foil stamping    HF-001      Shift 3   WO-1203    COR-002   COL-COR-002-033          17.93        12.25
22       6613  2025-10-29      INJECTION MOLDING    IM-002      Shift 2   WO-2660    COR-005   COL-COR-005-739         340.27       186.64
23      15974  2026-03-24      Hot Foil Stamping    HF-001      SHIFT 1   WO-1344    COR-008   COL-COR-008-414          13.32         9.63
24       6132  2025-10-22      INJECTION MOLDING    IM-001      Shift 3   WO-2152    COR-001   COL-COR-001-336         326.79       263.37
25      20380  2026-05-30      Injection Molding    IM-002      Shift 3   WO-2955    COR-005  COL-COR-005-1007          15.39        10.54
26      19056  2026-05-09         Blow Molding    ISBM-005    Shift 1     WO-7501    COR-005  COL-COR-005-1814          40.65        32.76
27        200  2025-07-21           BLOW MOLDING  ISBM-008      shift 1   WO-8614    COR-008  COL-COR-008-5968          27.97        17.55
28      13828  2026-02-18      Hot Foil Stamping    HF-001      Shift 1   WO-1296    COR-005   COL-COR-005-028          37.74        27.44
29      12176  2026-01-23      Hot Foil Stamping    HF-002      Shift 1   WO-1771    COR-001   COL-COR-001-215          28.56        13.47

In [5]:
# info() -- column names, dtypes, non-null counts
for name, df in raw_tables.items():
    print(f"\n{'='*100}\n{name}.info()\n{'='*100}")
    df.info()

====================================================================================================
fact_production_plan_raw.info()
====================================================================================================
<class 'pandas.DataFrame'>
RangeIndex: 9128 entries, 0 to 9127
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Date          9128 non-null   str
 1   Process       9128 non-null   str
 2   MachineId     9128 non-null   str
 3   ToolId        9128 non-null   str
 4   WorkOrder     9128 non-null   str
 5   PlannedQty    9128 non-null   int64
 6   StartTime     9128 non-null   str
 7   EndTime       9128 non-null   str
 8   PlannedHours  9128 non-null   float64
 9   ProductId     9128 non-null   str
dtypes: float64(1), int64(1), str(8)
memory usage: 713.3 KB

====================================================================================================
fact_production_raw.info()
====================================================================================================
<class 'pandas.DataFrame'>
RangeIndex: 9137 entries, 0 to 9136
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Date          9137 non-null   str
 1   Process       9137 non-null   str
 2   MachineId     9137 non-null   str
 3   ToolId        9137 non-null   str
 4   WorkOrder     9137 non-null   str
 5   ProductId     9137 non-null   str
 6   ProductBatch  9137 non-null   int64
 7   StartTime     9137 non-null   str
 8   EndTime       9137 non-null   str
 9   PlannedQty    9137 non-null   int64
 10  ProducedQty   9137 non-null   int64
 11  RejectedQty   9137 non-null   int64
 12  OperatorId    9111 non-null   str
dtypes: int64(4), str(9)
memory usage: 928.1 KB

====================================================================================================
fact_downtime_raw.info()
====================================================================================================
<class 'pandas.DataFrame'>
RangeIndex: 21874 entries, 0 to 21873
Data columns (total 10 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Date                   21874 non-null  str
 1   Process                21874 non-null  str
 2   MachineId              21874 non-null  str
 3   Shift                  21874 non-null  str
 4   StoppageStartTime      21874 non-null  str
 5   StoppageEndTime        21874 non-null  str
 6   PlannedStoppage        21874 non-null  str
 7   StoppageReason         21874 non-null  str
 8   MaintenanceTeam        21874 non-null  str
 9   MaintenanceTechnician  21810 non-null  str
dtypes: str(10)
memory usage: 1.7 MB

====================================================================================================
fact_material_consumption_raw.info()
====================================================================================================
<class 'pandas.DataFrame'>
RangeIndex: 23504 entries, 0 to 23503
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   RecordSeq      23504 non-null  int64
 1   Date           23504 non-null  str
 2   Process        23504 non-null  str
 3   MachineId      23504 non-null  str
 4   Shift          23504 non-null  str
 5   WorkOrder      23504 non-null  str
 6   MaterialId     23504 non-null  str
 7   MaterialLot    23468 non-null  str
 8   StartWeightKg  23504 non-null  float64
 9   EndWeightKg    23504 non-null  float64
dtypes: float64(2), int64(1), str(7)
memory usage: 1.8 MB

In [6]:
# isna().sum() -- exact missing-value count per column
for name, df in raw_tables.items():
    print(f"\n{'='*100}\n{name} -- missing values per column\n{'='*100}")
    print(df.isna().sum().to_string())

====================================================================================================
fact_production_plan_raw -- missing values per column
====================================================================================================
Date            0
Process         0
MachineId       0
ToolId          0
WorkOrder       0
PlannedQty      0
StartTime       0
EndTime         0
PlannedHours    0
ProductId       0

====================================================================================================
fact_production_raw -- missing values per column
====================================================================================================
Date             0
Process          0
MachineId        0
ToolId           0
WorkOrder        0
ProductId        0
ProductBatch     0
StartTime        0
EndTime          0
PlannedQty       0
ProducedQty      0
RejectedQty      0
OperatorId      26

====================================================================================================
fact_downtime_raw -- missing values per column
====================================================================================================
Date                      0
Process                   0
MachineId                 0
Shift                     0
StoppageStartTime         0
StoppageEndTime           0
PlannedStoppage           0
StoppageReason            0
MaintenanceTeam           0
MaintenanceTechnician    64

====================================================================================================
fact_material_consumption_raw -- missing values per column
====================================================================================================
RecordSeq         0
Date              0
Process           0
MachineId         0
Shift             0
WorkOrder         0
MaterialId        0
MaterialLot      36
StartWeightKg     0
EndWeightKg       0

## 2. Quality-control fact tables

Eight tables coming out of the quality lab / LIMS system: variable (X-bar/R)
measurements, attribute (AQL) inspections, and lot disposition decisions,
for the three decorated/molded product families -- caps, bottles, ink
(screen printing).

In [7]:
cq_files = {
    'fact_cap_inspection_variable_cq_raw': f'{RAW}/fact_cap_inspection_variable_cq_raw.csv',
    'fact_cap_attribute_inspection_cq_raw': f'{RAW}/fact_cap_attribute_inspection_cq_raw.csv',
    'fact_cap_disposition_lot_cq_raw': f'{RAW}/fact_cap_disposition_lot_cq_raw.csv',
    'fact_bottle_inspection_variables_cq_raw': f'{RAW}/fact_bottle_inspection_variables_cq_raw.csv',
    'fact_bottle_attribute_inspection_cq_raw': f'{RAW}/fact_bottle_attribute_inspection_cq_raw.csv',
    'fact_bottle_disposition_lot_cq_raw': f'{RAW}/fact_bottle_disposition_lot_cq_raw.csv',
    'fact_ink_attribute_inspection_cq_raw': f'{RAW}/fact_ink_attribute_inspection_cq_raw.csv',
    'fact_ink_disposition_lot_cq_raw': f'{RAW}/fact_ink_disposition_lot_cq_raw.csv',
}
cq_tables = {name: pd.read_csv(path, encoding='utf-8-sig') for name, path in cq_files.items()}
for name, df in cq_tables.items():
    print(f"{name}: {df.shape[0]:,} rows x {df.shape[1]} columns")

fact_cap_inspection_variable_cq_raw: 83,947 rows x 33 columns
fact_cap_attribute_inspection_cq_raw: 9,924 rows x 23 columns
fact_cap_disposition_lot_cq_raw: 1,654 rows x 22 columns
fact_bottle_inspection_variables_cq_raw: 124,580 rows x 27 columns
fact_bottle_attribute_inspection_cq_raw: 17,520 rows x 21 columns
fact_bottle_disposition_lot_cq_raw: 2,190 rows x 20 columns
fact_ink_attribute_inspection_cq_raw: 4,456 rows x 26 columns
fact_ink_disposition_lot_cq_raw: 557 rows x 22 columns

In [8]:
for name, df in cq_tables.items():
    print(f"\n{'='*100}\n{name} -- first 30 rows\n{'='*100}")
    display(df.head(30))

====================================================================================================
fact_cap_inspection_variable_cq_raw -- first 30 rows
====================================================================================================

,ProductBatch,WorkOrder,ProductionDate,Shift,MachineId,MoldId,CapId,Material,CapType,Characteristic,Equipment,Standard,Unit,InspectionDateTime,SampleGroup,LSL,Nominal,USL,M1,M2,M3,M4,M5,M6,M7,M8,M9,M10,XBar,RangeR,StdDevS,GroupResult,Inspector
0,LOTE-M-INJ-001-2490,WO-2248,2026-01-01,Shift 1,IM-001,M-INJ-001,TR-001-PETG-24410,PETG,Screw Cap,Weight,Scale 0.001 g,ISO 3951,g,2026-01-01 09:34:00.000,1,10.3,12.05,13.8,12.155,11.954,11.738,11.891,11.703,12.071,12.519,11.878,11.833,12.221,11.996,0.816,0.250,Conforming,Elena Santos
1,LOTE-M-INJ-001-2490,WO-2248,2026-01-01,SHIFT 1,IM-001,M-INJ-001,TR-001-PETG-24410,PETG,Screw Cap,Weight,Scale 0.001 g,ISO 3951,g,2026-01-01 10:04:00.000,2,10.3,12.05,13.8,12.087,11.724,12.040,12.293,11.580,11.890,11.385,11.599,11.405,11.968,11.797,0.909,0.306,Conforming,Elena Santos
2,LOTE-M-INJ-001-2490,WO-2248,2026-01-01,Shift 1,IM-001,M-INJ-001,TR-001-PETG-24410,PETG,Screw Cap,Weight,Scale 0.001 g,ISO 3951,g,2026-01-01 10:34:00.000,3,10.3,12.05,13.8,12.145,12.105,11.985,11.169,11.861,12.033,12.090,11.514,11.883,11.708,11.849,0.976,0.309,Conforming,Elena Santos
3,LOTE-M-INJ-001-2490,WO-2248,2026-01-01,SHIFT 1,IM-001,M-INJ-001,TR-001-PETG-24410,PETG,Screw Cap,Weight,Scale 0.001 g,ISO 3951,g,2026-01-01 11:04:00.000,4,10.3,12.05,13.8,12.421,11.767,12.039,12.360,11.846,12.011,12.089,12.072,11.621,12.077,12.030,0.800,0.245,Conforming,Elena Santos
4,LOTE-M-INJ-001-2490,WO-2248,2026-01-01,shift 1,IM-001,M-INJ-001,TR-001-PETG-24410,PETG,Screw Cap,Weight,Scale 0.001 g,ISO 3951,g,2026-01-01 11:34:00.000,5,10.3,12.05,13.8,11.508,12.351,12.092,11.825,12.750,12.317,11.630,12.076,12.252,11.984,12.079,1.242,0.367,Conforming,Elena Santos
5,LOTE-M-INJ-001-2490,WO-2248,2026-01-01,Shift 1,IM-001,M-INJ-001,TR-001-PETG-24410,PETG,Screw Cap,Weight,Scale 0.001 g,ISO 3951,g,2026-01-01 12:04:00.000,6,10.3,12.05,13.8,12.027,12.284,12.553,11.814,12.121,11.888,12.095,11.634,11.847,11.981,12.024,0.919,0.260,Conforming,Elena Santos
6,LOTE-M-INJ-001-2490,WO-2248,2026-01-01,shift 1,IM-001,M-INJ-001,TR-001-PETG-24410,PETG,Screw Cap,Weight,Scale 0.001 g,ISO 3951,g,2026-01-01 12:34:00.000,7,10.3,12.05,13.8,12.451,11.587,11.772,12.276,11.353,11.888,12.016,12.490,12.291,11.935,12.006,1.137,0.375,Conforming,Elena Santos
7,LOTE-M-INJ-001-2490,WO-2248,2026-01-01,Shift 1,IM-001,M-INJ-001,TR-001-PETG-24410,PETG,Screw Cap,Weight,Scale 0.001 g,ISO 3951,g,2026-01-01 13:04:00.000,8,10.3,12.05,13.8,11.962,12.583,11.900,11.944,12.173,12.008,11.981,11.660,12.046,11.895,12.015,0.923,0.238,Conforming,Elena Santos
8,LOTE-M-INJ-001-2490,WO-2248,2026-01-01,Shift 1,IM-001,M-INJ-001,TR-001-PETG-24410,PETG,Screw Cap,Weight,Scale 0.001 g,ISO 3951,g,2026-01-01 13:34:00.000,9,10.3,12.05,13.8,12.279,12.042,12.284,11.931,12.418,12.048,12.254,11.598,12.171,11.459,12.048,0.959,0.310,Conforming,Elena Santos
9,LOTE-M-INJ-001-2490,WO-2248,2026-01-01,SHIFT 2,IM-001,M-INJ-001,TR-001-PETG-24410,PETG,Screw Cap,Weight,Scale 0.001 g,ISO 3951,g,2026-01-01 14:04:00.000,10,10.3,12.05,13.8,11.943,11.735,12.107,12.836,11.759,11.832,12.122,12.223,11.988,11.978,12.052,1.101,0.318,Conforming,Elena Santos
10,LOTE-M-INJ-001-2490,WO-2248,2026-01-01,SHIFT 2,IM-001,M-INJ-001,TR-001-PETG-24410,PETG,Screw Cap,Weight,Scale 0.001 g,ISO 3951,g,2026-01-01 14:34:00.000,11,10.3,12.05,13.8,12.232,11.688,12.022,12.062,11.681,12.141,11.750,12.390,12.117,12.081,12.017,0.709,0.238,Conforming,Elena Santos
11,LOTE-M-INJ-001-2490,WO-2248,2026-01-01,Shift 2,IM-001,M-INJ-001,TR-001-PETG-24410,PETG,Screw Cap,Weight,Scale 0.001 g,ISO 3951,g,2026-01-01 15:04:00.000,12,10.3,12.05,13.8,12.008,11.351,11.654,12.177,11.305,12.346,11.439,12.315,11.754,12.323,11.867,1.041,0.419,Conforming,Elena Santos
12,LOTE-M-INJ-001-2490,WO-2248,2026-01-01,Shift 2,IM-001,M-INJ-001,TR-001-PETG-24410,PETG,Screw Cap,Weight,Scale 0.001 g,ISO 3951,g,2026-01-01 15:34:00.000,13,10.3,12.05,13.8,11.512,12.487,12.555,12.027,11.954,11.994,11.709,12.435,11.860,12.032,12.056,1.042,0.341,Conforming,Elena Santos
13,LOTE-M-INJ-001-2490,WO-2248,2026-01-01,Shift 2,IM-001,M-INJ-001,TR-001-PETG-24410,PETG,Screw Cap,Weight,Scale 0.001 g,ISO 3951,g,2026-01-01 16:04:00.000,14,10.3,12.05,13.8,11.831,11.603,12.490,11.996,12.388,12.055,11.807,11.936,11.854,12.053,12.001,0.887,0.268,Conforming,Elena Santos
14,LOTE-M-INJ-001-2490,WO-2248,2026-01-01,Shift 2,IM-001,M-INJ-001,TR-001-PETG-24410,PETG,Screw Cap,Weight,Scale 0.001 g,ISO 3951,g,2026-01-01 16:34:00.000,15,10.3,12.05,13.8,11.945,11.567,11.768,12.629,11.815,11.681,12.168,12.543,11.541,11.977,11.963,1.088,0.379,Conforming,Elena Santos
15,LOTE-M-INJ-001-2490,WO-2248,2026-01-01,Shift 2,IM-001,M-INJ-001,TR-001-PETG-24410,PETG,Screw Cap,Weight,Scale 0.001 g,ISO 3951,g,2026-01-01 17:04:00.000,16,10.3,12.05,13.8,11.434,12.307,12.042,12.075,11.787,12.209,11.861,12.000,11.662,11.624,11.900,0.874,0.276,Conforming,Elena Santos
16,LOTE-M-INJ-001-2490,WO-2248,2026-01-01,Shift 2,IM-001,M-INJ-001,TR-001-PETG-24410,PETG,Screw Cap,Weight,Scale 0.001 g,ISO 3951,g,2026-01-01 17:34:00.000,17,10.3,12.05,13.8,11.873,12.152,12.038,11.896,11.872,12.271,11.944,11.997,12.058,12.462,12.056,0.590,0.191,Conforming,Elena Santos
17,LOTE-M-INJ-001-2490,WO-2248,2026-01-01,shift 2,IM-001,M-INJ-001,TR-001-PETG-24410,PETG,Screw Cap,Weight,Scale 0.001 g,ISO 3951,g,2026-01-01 18:04:00.000,18,10.3,12.05,13.8,12.184,11.853,11.566,12.382,12.388,12.001,12.240,12.324,12.341,12.372,12.165,0.822,0.276,Conforming,Elena Santos
18,LOTE-M-INJ-001-2490,WO-2248,2026-01-01,Shift 2,IM-001,M-INJ-001,TR-001-PETG-24410,PETG,Screw Cap,Weight,Scale 0.001 g,ISO 3951,g,2026-01-01 18:34:00.000,19,10.3,12.05,13.8,12.580,11.614,12.352,12.223,12.356,12.708,12.570,11.649,11.459,12.336,12.185,1.249,0.447,Conforming,Elena Santos
19,LOTE-M-INJ-001-2490,WO-2248,2026-01-01,Shift 2,IM-001,M-INJ-001,TR-001-PETG-24410,PETG,Screw Cap,Weight,Scale 0.001 g,ISO 3951,g,2026-01-01 19:04:00.000,20,10.3,12.05,13.8,12.046,12.344,11.475,11.312,12.141,12.066,11.964,12.063,11.749,11.520,11.868,1.032,0.336,Conforming,Elena Santos
20,LOTE-M-INJ-001-2490,WO-2248,2026-01-01,Shift 2,IM-001,M-INJ-001,TR-001-PETG-24410,PETG,Screw Cap,Weight,Scale 0.001 g,ISO 3951,g,2026-01-01 19:34:00.000,21,10.3,12.05,13.8,11.710,11.475,12.227,12.029,12.192,11.704,11.820,11.700,11.740,12.118,11.871,0.752,0.253,Conforming,Elena Santos
21,LOTE-M-INJ-001-2490,WO-2248,2026-01-01,Shift 2,IM-001,M-INJ-001,TR-001-PETG-24410,PETG,Screw Cap,Weight,Scale 0.001 g,ISO 3951,g,2026-01-01 20:04:00.000,22,10.3,12.05,13.8,12.175,12.169,12.759,11.563,12.361,12.019,12.045,11.543,11.889,12.310,12.083,1.216,0.366,Conforming,Elena Santos
22,LOTE-M-INJ-001-2490,WO-2248,2026-01-01,Shift 2,IM-001,M-INJ-001,TR-001-PETG-24410,PETG,Screw Cap,Weight,Scale 0.001 g,ISO 3951,g,2026-01-01 20:34:00.000,23,10.3,12.05,13.8,12.078,11.948,12.454,12.042,11.280,11.808,11.361,10.912,11.864,12.517,11.826,1.605,0.511,Conforming,Elena Santos
23,LOTE-M-INJ-001-2490,WO-2248,2026-01-01,Shift 2,IM-001,M-INJ-001,TR-001-PETG-24410,PETG,Screw Cap,Weight,Scale 0.001 g,ISO 3951,g,2026-01-01 21:04:00.000,24,10.3,12.05,13.8,11.640,11.721,12.446,12.105,12.067,12.031,12.063,12.332,12.243,12.125,12.077,0.806,0.248,Conforming,Elena Santos
24,LOTE-M-INJ-001-2490,WO-2248,2026-01-01,Shift 2,IM-001,M-INJ-001,TR-001-PETG-24410,PETG,Screw Cap,Weight,Scale 0.001 g,ISO 3951,g,2026-01-01 21:34:00.000,25,10.3,12.05,13.8,12.229,11.811,12.433,11.605,12.002,12.047,11.586,12.653,12.561,11.888,12.081,1.066,0.379,Conforming,Elena Santos
25,LOTE-M-INJ-001-2490,WO-2248,2026-01-01,SHIFT 3,IM-001,M-INJ-001,TR-001-PETG-24410,PETG,Screw Cap,Weight,Scale 0.001 g,ISO 3951,g,2026-01-01 22:04:00.000,26,10.3,12.05,13.8,12.183,11.135,12.138,12.029,12.079,11.673,11.956,11.988,12.466,12.167,11.981,1.331,0.359,Conforming,Elena Santos
26,LOTE-M-INJ-001-2490,WO-2248,2026-01-01,shift 3,IM-001,M-INJ-001,TR-001-PETG-24410,PETG,Screw Cap,Weight,Scale 0.001 g,ISO 3951,g,2026-01-01 22:34:00.000,27,10.3,12.05,13.8,12.585,11.856,11.914,11.414,12.599,12.388,12.371,12.284,12.089,12.125,12.162,1.185,0.365,Conforming,Elena Santos
27,LOTE-M-INJ-001-2490,WO-2248,2026-01-01,Shift 3,IM-001,M-INJ-001,TR-001-PETG-24410,PETG,Screw Cap,Weight,Scale 0.001 g,ISO 3951,g,2026-01-01 23:04:00.000,28,10.3,12.05,13.8,11.979,12.069,12.579,12.244,12.030,11.847,11.828,12.611,12.227,12.074,12.149,0.783,0.271,Conforming,Elena Santos
28,LOTE-M-INJ-001-2490,WO-2248,2026-01-01,SHIFT 3,IM-001,M-INJ-001,TR-001-PETG-24410,PETG,Screw Cap,Weight,Scale 0.001 g,ISO 3951,g,2026-01-01 23:34:00.000,29,10.3,12.05,13.8,11.662,12.027,12.356,11.913,11.970,11.973,12.088,11.492,11.968,11.751,11.920,0.863,0.239,Conforming,Elena Santos
29,LOTE-M-INJ-001-2490,WO-2248,2026-01-01,Shift 3,IM-001,M-INJ-001,TR-001-PETG-24410,PETG,Screw Cap,Weight,Scale 0.001 g,ISO 3951,g,2026-01-02 00:04:00.000,30,10.3,12.05,13.8,11.780,12.252,12.584,11.940,11.839,12.117,12.049,11.702,12.211,12.755,12.123,1.053,0.342,Conforming,Elena Santos

====================================================================================================
fact_cap_attribute_inspection_cq_raw -- first 30 rows
====================================================================================================

,ProductBatch,WorkOrder,ProductionDate,Shift,MachineId,MoldId,CapId,Material,CapType,Characteristic,Class,AQL,Standard,InspectionLevel,LotSize,CodeLetter,SampleSize,AcceptanceNumber,RejectionNumber,DefectsFound,LotDecision,InspectionDateTime,Inspector
0,LOTE-M-INJ-001-2490,WO-2248,2026-01-01,Shift 2,IM-001,M-INJ-001,TR-001-PETG-24410,PETG,Screw Cap,Thread,Critical,0.10,ISO 2859-1,II,23450,M,315,0,1,0,Approved,2026-01-01 19:34:14.862,Elena Santos
1,LOTE-M-INJ-001-2490,WO-2248,2026-01-01,shift 3,IM-001,M-INJ-001,TR-001-PETG-24410,PETG,Screw Cap,Sealing,Critical,0.10,ISO 2859-1,II,23450,M,315,0,1,0,Approved,2026-01-02 01:30:59.992,Elena Santos
2,LOTE-M-INJ-001-2490,WO-2248,2026-01-01,Shift 3,IM-001,M-INJ-001,TR-001-PETG-24410,PETG,Screw Cap,Flash,Major,0.65,ISO 2859-1,II,23450,M,315,3,4,7,Rejected,2026-01-02 03:10:38.033,Elena Santos
3,LOTE-M-INJ-001-2490,WO-2248,2026-01-01,Shift 2,IM-001,M-INJ-001,TR-001-PETG-24410,PETG,Screw Cap,Short Shot,Major,0.65,ISO 2859-1,II,23450,M,315,3,4,0,Approved,2026-01-01 19:32:42.389,Elena Santos
4,LOTE-M-INJ-001-2490,WO-2248,2026-01-01,shift 3,IM-001,M-INJ-001,TR-001-PETG-24410,PETG,Screw Cap,Stain,Minor,1.50,ISO 2859-1,II,23450,M,315,14,15,0,Approved,2026-01-02 00:51:23.247,Elena Santos
5,LOTE-M-INJ-001-2490,WO-2248,2026-01-01,SHIFT 3,IM-001,M-INJ-001,TR-001-PETG-24410,PETG,Screw Cap,Color,Minor,1.50,ISO 2859-1,II,23450,M,315,14,15,1,Approved,2026-01-01 22:14:36.942,Elena Santos
6,LOTE-M-INJ-002-7520,WO-2751,2026-01-01,SHIFT 3,IM-002,M-INJ-002,TR-002-PP-PCR-24410,PP-PCR,Screw Cap,Thread,Critical,0.10,ISO 2859-1,II,6610,L,200,0,1,0,Approved,2026-01-01 22:45:11.449,Ana Silva
7,LOTE-M-INJ-002-7520,WO-2751,2026-01-01,Shift 3,IM-002,M-INJ-002,TR-002-PP-PCR-24410,PP-PCR,Screw Cap,Sealing,Critical,0.10,ISO 2859-1,II,6610,L,200,0,1,0,Approved,2026-01-01 22:35:06.825,Ana Silva
8,LOTE-M-INJ-002-7520,WO-2751,2026-01-01,Shift 2,IM-002,M-INJ-002,TR-002-PP-PCR-24410,PP-PCR,Screw Cap,Flash,Major,0.65,ISO 2859-1,II,6610,L,200,2,3,0,Approved,2026-01-01 21:57:27.728,Ana Silva
9,LOTE-M-INJ-002-7520,WO-2751,2026-01-01,Shift 3,IM-002,M-INJ-002,TR-002-PP-PCR-24410,PP-PCR,Screw Cap,Short Shot,Major,0.65,ISO 2859-1,II,6610,L,200,2,3,0,Approved,2026-01-01 22:16:43.698,Ana Silva
10,LOTE-M-INJ-002-7520,WO-2751,2026-01-01,Shift 2,IM-002,M-INJ-002,TR-002-PP-PCR-24410,PP-PCR,Screw Cap,Stain,Minor,1.50,ISO 2859-1,II,6610,L,200,10,11,1,Approved,2026-01-01 20:17:21.419,Ana Silva
11,LOTE-M-INJ-002-7520,WO-2751,2026-01-01,Shift 2,IM-002,M-INJ-002,TR-002-PP-PCR-24410,PP-PCR,Screw Cap,Color,Minor,1.50,ISO 2859-1,II,6610,L,200,10,11,0,Approved,2026-01-01 21:36:38.471,Ana Silva
12,LOTE-M-INJ-003-2430,WO-3242,2026-01-01,Shift 3,IM-003,M-INJ-003,TR-003-HDPE-24415,HDPE,Screw Cap,Thread,Critical,0.10,ISO 2859-1,II,25122,M,315,0,1,0,Approved,2026-01-02 01:12:00.062,Ana Silva
13,LOTE-M-INJ-003-2430,WO-3242,2026-01-01,Shift 3,IM-003,M-INJ-003,TR-003-HDPE-24415,HDPE,Screw Cap,Sealing,Critical,0.10,ISO 2859-1,II,25122,M,315,0,1,0,Approved,2026-01-01 22:41:26.309,Ana Silva
14,LOTE-M-INJ-003-2430,WO-3242,2026-01-01,shift 3,IM-003,M-INJ-003,TR-003-HDPE-24415,HDPE,Screw Cap,Flash,Major,0.65,ISO 2859-1,II,25122,M,315,3,4,0,Approved,2026-01-02 01:32:26.578,Ana Silva
15,LOTE-M-INJ-003-2430,WO-3242,2026-01-01,Shift 3,IM-003,M-INJ-003,TR-003-HDPE-24415,HDPE,Screw Cap,Short Shot,Major,0.65,ISO 2859-1,II,25122,M,315,3,4,0,Approved,2026-01-01 22:13:37.354,Ana Silva
16,LOTE-M-INJ-003-2430,WO-3242,2026-01-01,Shift 2,IM-003,M-INJ-003,TR-003-HDPE-24415,HDPE,Screw Cap,Stain,Minor,1.50,ISO 2859-1,II,25122,M,315,14,15,2,Approved,2026-01-01 20:58:56.649,Ana Silva
17,LOTE-M-INJ-003-2430,WO-3242,2026-01-01,shift 3,IM-003,M-INJ-003,TR-003-HDPE-24415,HDPE,Screw Cap,Color,Minor,1.50,ISO 2859-1,II,25122,M,315,14,15,0,Approved,2026-01-02 02:05:19.395,Ana Silva
18,LOTE-M-INJ-004-7680,WO-3767,2026-01-01,Shift 2,IM-004,M-INJ-004,TR-004-PETG-28410,PETG,Screw Cap,Thread,Critical,0.10,ISO 2859-1,II,14915,M,315,0,1,0,Approved,2026-01-01 21:11:27.474,Carlos Mendes
19,LOTE-M-INJ-004-7680,WO-3767,2026-01-01,Shift 2,IM-004,M-INJ-004,TR-004-PETG-28410,PETG,Screw Cap,Sealing,Critical,0.10,ISO 2859-1,II,14915,M,315,0,1,0,Approved,2026-01-01 20:55:01.296,Carlos Mendes
20,LOTE-M-INJ-004-7680,WO-3767,2026-01-01,shift 3,IM-004,M-INJ-004,TR-004-PETG-28410,PETG,Screw Cap,Flash,Major,0.65,ISO 2859-1,II,14915,M,315,3,4,0,Approved,2026-01-02 00:42:09.038,Carlos Mendes
21,LOTE-M-INJ-004-7680,WO-3767,2026-01-01,Shift 3,IM-004,M-INJ-004,TR-004-PETG-28410,PETG,Screw Cap,Short Shot,Major,0.65,ISO 2859-1,II,14915,M,315,3,4,0,Approved,2026-01-02 00:53:13.349,Carlos Mendes
22,LOTE-M-INJ-004-7680,WO-3767,2026-01-01,Shift 2,IM-004,M-INJ-004,TR-004-PETG-28410,PETG,Screw Cap,Stain,Minor,1.50,ISO 2859-1,II,14915,M,315,14,15,0,Approved,2026-01-01 21:36:44.251,Carlos Mendes
23,LOTE-M-INJ-004-7680,WO-3767,2026-01-01,Shift 3,IM-004,M-INJ-004,TR-004-PETG-28410,PETG,Screw Cap,Color,Minor,1.50,ISO 2859-1,II,14915,M,315,14,15,0,Approved,2026-01-02 01:26:27.142,Carlos Mendes
24,LOTE-M-INJ-008-2680,WO-4267,2026-01-01,Shift 1,IM-005,M-INJ-008,TF-008-PP-PCR-28410,PP-PCR,Screw Cap,Thread,Critical,0.10,ISO 2859-1,II,6816,L,200,0,1,0,Approved,2026-01-01 10:46:58.648,Diogo Ferreira
25,LOTE-M-INJ-008-2680,WO-4267,2026-01-01,Shift 1,IM-005,M-INJ-008,TF-008-PP-PCR-28410,PP-PCR,Screw Cap,Sealing,Critical,0.10,ISO 2859-1,II,6816,L,200,0,1,0,Approved,2026-01-01 08:37:49.409,Diogo Ferreira
26,LOTE-M-INJ-008-2680,WO-4267,2026-01-01,Shift 1,IM-005,M-INJ-008,TF-008-PP-PCR-28410,PP-PCR,Screw Cap,Flash,Major,0.65,ISO 2859-1,II,6816,L,200,2,3,0,Approved,2026-01-01 07:49:03.982,Diogo Ferreira
27,LOTE-M-INJ-008-2680,WO-4267,2026-01-01,Shift 1,IM-005,M-INJ-008,TF-008-PP-PCR-28410,PP-PCR,Screw Cap,Short Shot,Major,0.65,ISO 2859-1,II,6816,L,200,2,3,0,Approved,2026-01-01 07:57:12.053,Diogo Ferreira
28,LOTE-M-INJ-008-2680,WO-4267,2026-01-01,Shift 1,IM-005,M-INJ-008,TF-008-PP-PCR-28410,PP-PCR,Screw Cap,Stain,Minor,1.50,ISO 2859-1,II,6816,L,200,10,11,0,Approved,2026-01-01 10:31:08.463,Diogo Ferreira
29,LOTE-M-INJ-008-2680,WO-4267,2026-01-01,Shift 1,IM-005,M-INJ-008,TF-008-PP-PCR-28410,PP-PCR,Screw Cap,Color,Minor,1.50,ISO 2859-1,II,6816,L,200,10,11,0,Approved,2026-01-01 09:35:31.842,Diogo Ferreira

====================================================================================================
fact_cap_disposition_lot_cq_raw -- first 30 rows
====================================================================================================

,ProductBatch,WorkOrder,ProductionDate,Shift,MachineId,MoldId,CapId,Material,CapType,LotSize,CodeLetter,SampleSize,CriticalDefects,MajorDefects,MinorDefects,TotalSampleDefects,VariablesDecision,AttributesDecision,FinalLotDecision,LotDecisionDateTime,Remarks,Inspector
0,LOTE-M-INJ-001-2490,WO-2248,2026-01-01,Shift 1,IM-001,M-INJ-001,TR-001-PETG-24410,PETG,Screw Cap,23450,M,315,0,7,0,7,Nonconformance Detected,Rejected,Rejected,2026-01-02 05:44:58.547,Flash:7(Re=4),Elena Santos
1,LOTE-M-INJ-002-7520,WO-2751,2026-01-01,SHIFT 2,IM-002,M-INJ-002,TR-002-PP-PCR-24410,PP-PCR,Screw Cap,6610,L,200,0,0,0,0,Conforming,Approved,Approved,2026-01-02 01:17:47.378,—,Ana Silva
2,LOTE-M-INJ-003-2430,WO-3242,2026-01-01,SHIFT 1,IM-003,M-INJ-003,TR-003-HDPE-24415,HDPE,Screw Cap,25122,M,315,0,0,0,0,Nonconformance Detected,Approved,Approved,2026-01-02 06:14:59.329,—,Ana Silva
3,LOTE-M-INJ-004-7680,WO-3767,2026-01-01,SHIFT 1,IM-004,M-INJ-004,TR-004-PETG-28410,PETG,Screw Cap,14915,M,315,0,0,0,0,Nonconformance Detected,Approved,Approved,2026-01-02 04:11:09.965,—,Carlos Mendes
4,LOTE-M-INJ-008-2680,WO-4267,2026-01-01,Shift 3,IM-005,M-INJ-008,TF-008-PP-PCR-28410,PP-PCR,Screw Cap,6816,L,200,0,0,0,0,Conforming,Approved,Approved,2026-01-01 13:09:24.768,—,Diogo Ferreira
5,LOTE-M-INJ-005-2690,WO-4268,2026-01-01,Shift 1,IM-005,M-INJ-005,TF-005-HDPE-24410,HDPE,Screw Cap,17053,M,315,1,0,0,1,Conforming,Rejected,Rejected,2026-01-02 11:42:24.937,Sealing:1(Re=1),Elena Santos
6,LOTE-M-INJ-009-7800,WO-4779,2026-01-01,Shift 1,IM-006,M-INJ-009,TF-009-PP-28415,PP,Screw Cap,7306,L,200,0,0,0,0,Conforming,Approved,Approved,2026-01-02 02:41:47.823,—,Carlos Mendes
7,LOTE-M-INJ-001-2500,WO-2249,2026-01-02,Shift 3,IM-001,M-INJ-001,TR-001-PETG-24410,PETG,Screw Cap,8236,L,200,0,0,0,0,Nonconformance Detected,Approved,Approved,2026-01-02 13:08:32.690,—,Diogo Ferreira
8,LOTE-M-INJ-001-2510,WO-2250,2026-01-02,Shift 1,IM-001,M-INJ-001,TR-001-PETG-24410,PETG,Screw Cap,15230,M,315,0,0,0,0,Nonconformance Detected,Approved,Approved,2026-01-03 01:54:57.597,—,Carlos Mendes
9,LOTE-M-INJ-002-7530,WO-2752,2026-01-02,SHIFT 3,IM-002,M-INJ-002,TR-002-PP-PCR-24410,PP-PCR,Screw Cap,6947,L,200,0,0,0,0,Nonconformance Detected,Approved,Approved,2026-01-02 10:36:57.008,—,Carlos Mendes
10,LOTE-M-INJ-002-7540,WO-2753,2026-01-02,Shift 1,IM-002,M-INJ-002,TR-002-PP-PCR-24410,PP-PCR,Screw Cap,9396,L,200,0,0,0,0,Nonconformance Detected,Approved,Approved,2026-01-02 23:57:56.661,—,Elena Santos
11,LOTE-M-INJ-002-7550,WO-2754,2026-01-02,Shift 3,IM-002,M-INJ-002,TR-002-PP-PCR-24410,PP-PCR,Screw Cap,13477,M,315,0,0,0,0,Nonconformance Detected,Approved,Approved,2026-01-03 16:46:43.342,—,Carlos Mendes
12,LOTE-M-INJ-003-2440,WO-3243,2026-01-02,Shift 3,IM-003,M-INJ-003,TR-003-HDPE-24415,HDPE,Screw Cap,22016,M,315,0,0,0,0,Nonconformance Detected,Approved,Approved,2026-01-02 19:21:13.000,—,Ana Silva
13,LOTE-M-INJ-003-2450,WO-3244,2026-01-02,Shift 2,IM-003,M-INJ-003,TR-003-HDPE-24415,HDPE,Screw Cap,9624,L,200,0,0,0,0,Nonconformance Detected,Approved,Approved,2026-01-03 01:18:53.924,—,Carlos Mendes
14,LOTE-M-INJ-004-7690,WO-3768,2026-01-02,shift 3,IM-004,M-INJ-004,TR-004-PETG-28410,PETG,Screw Cap,6666,L,200,0,0,0,0,Conforming,Approved,Approved,2026-01-02 09:55:53.214,—,Carlos Mendes
15,LOTE-M-INJ-004-7700,WO-3769,2026-01-02,Shift 1,IM-004,M-INJ-004,TR-004-PETG-28410,PETG,Screw Cap,15726,M,315,0,0,0,0,Nonconformance Detected,Approved,Approved,2026-01-02 23:35:47.347,—,Diogo Ferreira
16,LOTE-M-INJ-004-7710,WO-3770,2026-01-02,Shift 3,IM-004,M-INJ-004,TR-004-PETG-28410,PETG,Screw Cap,9554,L,200,0,0,0,0,Nonconformance Detected,Approved,Approved,2026-01-03 09:09:28.177,—,Elena Santos
17,LOTE-M-INJ-008-2700,WO-4269,2026-01-02,shift 1,IM-005,M-INJ-008,TF-008-PP-PCR-28410,PP-PCR,Screw Cap,5684,L,200,0,0,0,0,Conforming,Approved,Approved,2026-01-02 19:39:40.966,—,Beatriz Costa
18,LOTE-M-INJ-008-2710,WO-4270,2026-01-02,Shift 2,IM-005,M-INJ-008,TF-008-PP-PCR-28410,PP-PCR,Screw Cap,7358,L,200,0,0,0,0,Conforming,Approved,Approved,2026-01-03 04:27:54.727,—,Beatriz Costa
19,LOTE-M-INJ-009-7810,WO-4780,2026-01-02,Shift 3,IM-006,M-INJ-009,TF-009-PP-28415,PP,Screw Cap,4073,L,200,0,0,0,0,Conforming,Approved,Approved,2026-01-02 09:45:47.001,—,Elena Santos
20,LOTE-M-INJ-009-7820,WO-4781,2026-01-02,Shift 1,IM-006,M-INJ-009,TF-009-PP-PCR-28415,PP-PCR,Screw Cap,5608,L,200,0,0,0,0,Conforming,Approved,Approved,2026-01-02 20:53:22.467,—,Carlos Mendes
21,LOTE-M-INJ-009-7830,WO-4782,2026-01-02,shift 2,IM-006,M-INJ-009,TF-009-PP-PCR-28415,PP-PCR,Screw Cap,7032,L,200,0,0,0,0,Nonconformance Detected,Approved,Approved,2026-01-03 08:43:09.546,—,Elena Santos
22,LOTE-M-INJ-001-2520,WO-2251,2026-01-03,shift 3,IM-001,M-INJ-001,TR-001-PP-24410,PP,Screw Cap,14543,M,315,1,0,0,1,Nonconformance Detected,Rejected,Rejected,2026-01-03 15:30:27.019,Thread:1(Re=1),Beatriz Costa
23,LOTE-M-INJ-001-2530,WO-2252,2026-01-03,Shift 2,IM-001,M-INJ-001,TR-001-PETG-24410,PETG,Screw Cap,7336,L,200,0,0,0,0,Nonconformance Detected,Approved,Approved,2026-01-03 23:09:07.933,—,Ana Silva
24,LOTE-M-INJ-002-7560,WO-2755,2026-01-03,Shift 2,IM-002,M-INJ-002,TR-002-PP-24410,PP,Screw Cap,4750,L,200,0,0,0,0,Conforming,Approved,Approved,2026-01-03 22:21:38.267,—,Ana Silva
25,LOTE-M-INJ-003-2460,WO-3245,2026-01-03,Shift 3,IM-003,M-INJ-003,TR-003-HDPE-24415,HDPE,Screw Cap,8608,L,200,0,0,0,0,Conforming,Approved,Approved,2026-01-03 07:51:10.683,—,Elena Santos
26,LOTE-M-INJ-003-2470,WO-3246,2026-01-03,SHIFT 1,IM-003,M-INJ-003,TR-003-PP-24415,PP,Screw Cap,13926,M,315,0,0,0,0,Conforming,Approved,Approved,2026-01-03 18:27:11.063,—,Beatriz Costa
27,LOTE-M-INJ-003-2480,WO-3247,2026-01-03,Shift 2,IM-003,M-INJ-003,TR-003-HDPE-24415,HDPE,Screw Cap,6823,L,200,0,0,0,0,Conforming,Approved,Approved,2026-01-03 22:41:50.849,—,Carlos Mendes
28,LOTE-M-INJ-004-7720,WO-3771,2026-01-03,Shift 1,IM-004,M-INJ-004,TR-004-PETG-28410,PETG,Screw Cap,7770,L,200,0,0,0,0,Conforming,Approved,Approved,2026-01-03 14:47:07.424,—,Ana Silva
29,LOTE-M-INJ-007-7730,WO-3772,2026-01-03,Shift 2,IM-004,M-INJ-007,TF-007-HDPE-28410,HDPE,Screw Cap,4443,L,200,0,0,0,0,Nonconformance Detected,Approved,Approved,2026-01-03 22:53:25.739,—,Ana Silva

====================================================================================================
fact_bottle_inspection_variables_cq_raw -- first 30 rows
====================================================================================================

,ProductBatch,WorkOrder,ProductionDate,Shift,MachineId,MoldId,BottleId,Material,Characteristic,Equipment,Standard,Unit,InspectionDateTime,SampleGroup,LSL,Nominal,USL,M1,M2,M3,M4,M5,XBar,RangeR,StdDevS,GroupResult,Inspector
0,LOTE-M-SOP-007-2950,WO-5294,2026-01-01,Shift 3,ISBM-001,M-SOP-007,FR-007-PP-350,PP,Weight,Scale 0.01 g,ISO 3951,g,2026-01-01 01:21:00.000,1,24.432,29.330,34.228,28.605,29.189,30.331,29.599,30.476,29.640,1.871,0.783,Conforming,Beatriz Costa
1,LOTE-M-SOP-007-2950,WO-5294,2026-01-01,Shift 3,ISBM-001,M-SOP-007,FR-007-PP-350,PP,Weight,Scale 0.01 g,ISO 3951,g,2026-01-01 01:51:00.000,2,24.432,29.330,34.228,29.643,30.557,28.089,29.526,28.611,29.285,2.468,0.960,Conforming,Beatriz Costa
2,LOTE-M-SOP-007-2950,WO-5294,2026-01-01,Shift 3,ISBM-001,M-SOP-007,FR-007-PP-350,PP,Weight,Scale 0.01 g,ISO 3951,g,2026-01-01 02:21:00.000,3,24.432,29.330,34.228,28.217,29.340,28.904,29.271,28.473,28.841,1.123,0.491,Conforming,Beatriz Costa
3,LOTE-M-SOP-007-2950,WO-5294,2026-01-01,Shift 3,ISBM-001,M-SOP-007,FR-007-PP-350,PP,Weight,Scale 0.01 g,ISO 3951,g,2026-01-01 02:51:00.000,4,24.432,29.330,34.228,29.946,32.781,30.760,29.409,27.520,30.083,5.261,1.922,Conforming,Beatriz Costa
4,LOTE-M-SOP-007-2950,WO-5294,2026-01-01,Shift 3,ISBM-001,M-SOP-007,FR-007-PP-350,PP,Weight,Scale 0.01 g,ISO 3951,g,2026-01-01 03:21:00.000,5,24.432,29.330,34.228,30.537,28.867,28.573,29.984,29.229,29.438,1.964,0.810,Conforming,Beatriz Costa
5,LOTE-M-SOP-007-2950,WO-5294,2026-01-01,Shift 3,ISBM-001,M-SOP-007,FR-007-PP-350,PP,Weight,Scale 0.01 g,ISO 3951,g,2026-01-01 03:51:00.000,6,24.432,29.330,34.228,28.801,29.252,30.760,28.801,28.222,29.167,2.538,0.962,Conforming,Beatriz Costa
6,LOTE-M-SOP-007-2950,WO-5294,2026-01-01,Shift 3,ISBM-001,M-SOP-007,FR-007-PP-350,PP,Weight,Scale 0.01 g,ISO 3951,g,2026-01-01 04:21:00.000,7,24.432,29.330,34.228,30.315,29.941,29.407,29.145,29.239,29.609,1.170,0.501,Conforming,Beatriz Costa
7,LOTE-M-SOP-007-2950,WO-5294,2026-01-01,Shift 3,ISBM-001,M-SOP-007,FR-007-PP-350,PP,Weight,Scale 0.01 g,ISO 3951,g,2026-01-01 04:51:00.000,8,24.432,29.330,34.228,27.447,30.753,28.872,28.605,28.606,28.857,3.306,1.195,Conforming,Beatriz Costa
8,LOTE-M-SOP-007-2950,WO-5294,2026-01-01,Shift 3,ISBM-001,M-SOP-007,FR-007-PP-350,PP,Weight,Scale 0.01 g,ISO 3951,g,2026-01-01 05:21:00.000,9,24.432,29.330,34.228,29.485,30.718,29.576,29.061,28.648,29.498,2.070,0.776,Conforming,Beatriz Costa
9,LOTE-M-SOP-007-2950,WO-5294,2026-01-01,Shift 3,ISBM-001,M-SOP-007,FR-007-PP-350,PP,Weight,Scale 0.01 g,ISO 3951,g,2026-01-01 05:51:00.000,10,24.432,29.330,34.228,29.263,28.001,30.134,28.372,29.725,29.099,2.134,0.898,Conforming,Beatriz Costa
10,LOTE-M-SOP-007-2950,WO-5294,2026-01-01,Shift 1,ISBM-001,M-SOP-007,FR-007-PP-350,PP,Weight,Scale 0.01 g,ISO 3951,g,2026-01-01 06:21:00.000,11,24.432,29.330,34.228,28.664,29.958,29.642,29.015,29.047,29.265,1.294,0.523,Conforming,Beatriz Costa
11,LOTE-M-SOP-007-2950,WO-5294,2026-01-01,Shift 1,ISBM-001,M-SOP-007,FR-007-PP-350,PP,Weight,Scale 0.01 g,ISO 3951,g,2026-01-01 06:51:00.000,12,24.432,29.330,34.228,28.609,29.387,29.917,28.008,29.029,28.990,1.909,0.729,Conforming,Beatriz Costa
12,LOTE-M-SOP-007-2950,WO-5294,2026-01-01,Shift 3,ISBM-001,M-SOP-007,FR-007-PP-350,PP,Height,Caliper,ISO 3951,mm,2026-01-01 01:21:00.000,1,58.484,59.800,61.116,59.703,60.235,59.803,59.816,59.842,59.880,0.531,0.205,Conforming,Beatriz Costa
13,LOTE-M-SOP-007-2950,WO-5294,2026-01-01,Shift 3,ISBM-001,M-SOP-007,FR-007-PP-350,PP,Height,Caliper,ISO 3951,mm,2026-01-01 02:21:00.000,2,58.484,59.800,61.116,59.675,59.802,59.320,60.241,59.731,59.754,0.922,0.330,Conforming,Beatriz Costa
14,LOTE-M-SOP-007-2950,WO-5294,2026-01-01,Shift 3,ISBM-001,M-SOP-007,FR-007-PP-350,PP,Height,Caliper,ISO 3951,mm,2026-01-01 03:21:00.000,3,58.484,59.800,61.116,59.643,59.837,60.022,59.398,60.257,59.831,0.858,0.332,Conforming,Beatriz Costa
15,LOTE-M-SOP-007-2950,WO-5294,2026-01-01,Shift 3,ISBM-001,M-SOP-007,FR-007-PP-350,PP,Height,Caliper,ISO 3951,mm,2026-01-01 04:21:00.000,4,58.484,59.800,61.116,60.305,59.665,59.337,59.623,59.684,59.723,0.968,0.354,Conforming,Beatriz Costa
16,LOTE-M-SOP-007-2950,WO-5294,2026-01-01,Shift 3,ISBM-001,M-SOP-007,FR-007-PP-350,PP,Height,Caliper,ISO 3951,mm,2026-01-01 05:21:00.000,5,58.484,59.800,61.116,59.882,59.681,60.015,59.909,60.532,60.004,0.851,0.319,Conforming,Beatriz Costa
17,LOTE-M-SOP-007-2950,WO-5294,2026-01-01,Shift 1,ISBM-001,M-SOP-007,FR-007-PP-350,PP,Height,Caliper,ISO 3951,mm,2026-01-01 06:21:00.000,6,58.484,59.800,61.116,59.958,60.024,59.772,59.462,59.853,59.814,0.562,0.219,Conforming,Beatriz Costa
18,LOTE-M-SOP-007-2950,WO-5294,2026-01-01,Shift 3,ISBM-001,M-SOP-007,FR-007-PP-350,PP,Neck Diameter,Gauge,ISO 3951,mm,2026-01-01 01:21:00.000,1,23.700,24.000,24.300,23.959,23.991,24.030,24.004,23.906,23.978,0.124,0.048,Conforming,Beatriz Costa
19,LOTE-M-SOP-007-2950,WO-5294,2026-01-01,Shift 3,ISBM-001,M-SOP-007,FR-007-PP-350,PP,Neck Diameter,Gauge,ISO 3951,mm,2026-01-01 02:21:00.000,2,23.700,24.000,24.300,24.054,23.969,24.065,24.000,23.962,24.010,0.104,0.048,Conforming,Beatriz Costa
20,LOTE-M-SOP-007-2950,WO-5294,2026-01-01,Shift 3,ISBM-001,M-SOP-007,FR-007-PP-350,PP,Neck Diameter,Gauge,ISO 3951,mm,2026-01-01 03:21:00.000,3,23.700,24.000,24.300,24.002,23.985,24.135,23.945,24.116,24.037,0.190,0.084,Conforming,Beatriz Costa
21,LOTE-M-SOP-007-2950,WO-5294,2026-01-01,Shift 3,ISBM-001,M-SOP-007,FR-007-PP-350,PP,Neck Diameter,Gauge,ISO 3951,mm,2026-01-01 04:21:00.000,4,23.700,24.000,24.300,23.907,24.023,23.986,24.020,24.070,24.001,0.163,0.061,Conforming,Beatriz Costa
22,LOTE-M-SOP-007-2950,WO-5294,2026-01-01,Shift 3,ISBM-001,M-SOP-007,FR-007-PP-350,PP,Neck Diameter,Gauge,ISO 3951,mm,2026-01-01 05:21:00.000,5,23.700,24.000,24.300,24.018,23.988,24.028,24.141,23.969,24.029,0.172,0.067,Conforming,Beatriz Costa
23,LOTE-M-SOP-007-2950,WO-5294,2026-01-01,Shift 1,ISBM-001,M-SOP-007,FR-007-PP-350,PP,Neck Diameter,Gauge,ISO 3951,mm,2026-01-01 06:21:00.000,6,23.700,24.000,24.300,23.949,24.031,23.905,24.000,23.887,23.954,0.144,0.061,Conforming,Beatriz Costa
24,LOTE-M-SOP-007-2950,WO-5294,2026-01-01,Shift 3,ISBM-001,M-SOP-007,FR-007-PP-350,PP,Thickness,Thickness Gauge,ISO 3951,mm,2026-01-01 01:21:00.000,1,0.463,0.735,1.007,0.673,0.770,0.729,0.652,0.732,0.711,0.119,0.048,Conforming,Beatriz Costa
25,LOTE-M-SOP-007-2950,WO-5294,2026-01-01,Shift 3,ISBM-001,M-SOP-007,FR-007-PP-350,PP,Thickness,Thickness Gauge,ISO 3951,mm,2026-01-01 03:21:00.000,2,0.463,0.735,1.007,0.733,0.770,0.795,0.785,0.676,0.752,0.120,0.049,Conforming,Beatriz Costa
26,LOTE-M-SOP-007-2950,WO-5294,2026-01-01,Shift 3,ISBM-001,M-SOP-007,FR-007-PP-350,PP,Thickness,Thickness Gauge,ISO 3951,mm,2026-01-01 05:21:00.000,3,0.463,0.735,1.007,0.698,0.820,0.746,0.625,0.777,0.733,0.195,0.075,Conforming,Beatriz Costa
27,LOTE-M-SOP-007-2950,WO-5294,2026-01-01,Shift 3,ISBM-001,M-SOP-007,FR-007-PP-350,PP,Overflow Volume,Graduated Cylinder,ISO 3951,ml,2026-01-01 05:50:23.650,1,347.510,352.800,358.090,353.220,353.980,351.100,NaN,NaN,352.770,2.880,1.490,Conforming,Beatriz Costa
28,LOTE-M-SOP-001-2960,WO-5295,2026-01-01,Shift 1,ISBM-001,M-SOP-001,FR-001-HDPE-300,HDPE,Weight,Scale 0.01 g,ISO 3951,g,2026-01-01 08:24:00.000,1,21.425,25.720,30.015,25.461,26.562,25.439,24.331,26.468,25.652,2.231,0.911,Conforming,Diogo Ferreira
29,LOTE-M-SOP-001-2960,WO-5295,2026-01-01,Shift 1,ISBM-001,M-SOP-001,FR-001-HDPE-300,HDPE,Weight,Scale 0.01 g,ISO 3951,g,2026-01-01 08:54:00.000,2,21.425,25.720,30.015,23.989,25.928,25.085,25.836,24.126,24.993,1.939,0.916,Conforming,Diogo Ferreira

====================================================================================================
fact_bottle_attribute_inspection_cq_raw -- first 30 rows
====================================================================================================

,ProductBatch,WorkOrder,ProductionDate,MachineId,MoldId,BottleId,Material,Characteristic,Class,AQL,Standard,InspectionLevel,LotSize,CodeLetter,SampleSize,AcceptanceNumber,RejectionNumber,DefectsFound,LotDecision,InspectionDateTime,Inspector
0,LOTE-M-SOP-007-2950,WO-5294,2026-01-01,ISBM-001,M-SOP-007,FR-007-PP-350,PP,Leakage,Critical,0.10,ISO 2859-1,II,3554,L,200,0,1,0,Approved,2026-01-01 05:10:49.749,Beatriz Costa
1,LOTE-M-SOP-007-2950,WO-5294,2026-01-01,ISBM-001,M-SOP-007,FR-007-PP-350,PP,Flash,Major,0.65,ISO 2859-1,II,3554,L,200,2,3,0,Approved,2026-01-01 04:34:27.349,Beatriz Costa
2,LOTE-M-SOP-007-2950,WO-5294,2026-01-01,ISBM-001,M-SOP-007,FR-007-PP-350,PP,Bubbles,Major,0.65,ISO 2859-1,II,3554,L,200,2,3,1,Approved,2026-01-01 05:06:09.012,Beatriz Costa
3,LOTE-M-SOP-007-2950,WO-5294,2026-01-01,ISBM-001,M-SOP-007,FR-007-PP-350,PP,Black Specks,Minor,1.50,ISO 2859-1,II,3554,L,200,10,11,0,Approved,2026-01-01 05:04:02.074,Beatriz Costa
4,LOTE-M-SOP-007-2950,WO-5294,2026-01-01,ISBM-001,M-SOP-007,FR-007-PP-350,PP,Stain,Minor,1.50,ISO 2859-1,II,3554,L,200,10,11,0,Approved,2026-01-01 05:38:23.288,Beatriz Costa
5,LOTE-M-SOP-007-2950,WO-5294,2026-01-01,ISBM-001,M-SOP-007,FR-007-PP-350,PP,Transparency,Minor,1.50,ISO 2859-1,II,3554,L,200,10,11,1,Approved,2026-01-01 06:05:56.682,Beatriz Costa
6,LOTE-M-SOP-007-2950,WO-5294,2026-01-01,ISBM-001,M-SOP-007,FR-007-PP-350,PP,Color,Minor,1.50,ISO 2859-1,II,3554,L,200,10,11,0,Approved,2026-01-01 04:57:29.829,Beatriz Costa
7,LOTE-M-SOP-007-2950,WO-5294,2026-01-01,ISBM-001,M-SOP-007,FR-007-PP-350,PP,Burr,Major,0.65,ISO 2859-1,II,3554,L,200,2,3,0,Approved,2026-01-01 04:31:56.480,Beatriz Costa
8,LOTE-M-SOP-001-2960,WO-5295,2026-01-01,ISBM-001,M-SOP-001,FR-001-HDPE-300,HDPE,Leakage,Critical,0.10,ISO 2859-1,II,10738,M,315,0,1,0,Approved,2026-01-01 22:29:45.966,Diogo Ferreira
9,LOTE-M-SOP-001-2960,WO-5295,2026-01-01,ISBM-001,M-SOP-001,FR-001-HDPE-300,HDPE,Flash,Major,0.65,ISO 2859-1,II,10738,M,315,3,4,0,Approved,2026-01-01 22:53:06.902,Diogo Ferreira
10,LOTE-M-SOP-001-2960,WO-5295,2026-01-01,ISBM-001,M-SOP-001,FR-001-HDPE-300,HDPE,Bubbles,Major,0.65,ISO 2859-1,II,10738,M,315,3,4,1,Approved,2026-01-01 19:38:31.072,Diogo Ferreira
11,LOTE-M-SOP-001-2960,WO-5295,2026-01-01,ISBM-001,M-SOP-001,FR-001-HDPE-300,HDPE,Black Specks,Minor,1.50,ISO 2859-1,II,10738,M,315,14,15,0,Approved,2026-01-01 18:40:47.716,Diogo Ferreira
12,LOTE-M-SOP-001-2960,WO-5295,2026-01-01,ISBM-001,M-SOP-001,FR-001-HDPE-300,HDPE,Stain,Minor,1.50,ISO 2859-1,II,10738,M,315,14,15,0,Approved,2026-01-01 22:27:59.521,Diogo Ferreira
13,LOTE-M-SOP-001-2960,WO-5295,2026-01-01,ISBM-001,M-SOP-001,FR-001-HDPE-300,HDPE,Transparency,Minor,1.50,ISO 2859-1,II,10738,M,315,14,15,0,Approved,2026-01-01 22:18:43.194,Diogo Ferreira
14,LOTE-M-SOP-001-2960,WO-5295,2026-01-01,ISBM-001,M-SOP-001,FR-001-HDPE-300,HDPE,Color,Minor,1.50,ISO 2859-1,II,10738,M,315,14,15,1,Approved,2026-01-01 18:28:48.155,Diogo Ferreira
15,LOTE-M-SOP-001-2960,WO-5295,2026-01-01,ISBM-001,M-SOP-001,FR-001-HDPE-300,HDPE,Burr,Major,0.65,ISO 2859-1,II,10738,M,315,3,4,0,Approved,2026-01-02 01:19:42.454,Diogo Ferreira
16,LOTE-M-SOP-008-8110,WO-5810,2026-01-01,ISBM-002,M-SOP-008,FR-008-PET-350,PET,Leakage,Critical,0.10,ISO 2859-1,II,9293,L,200,0,1,0,Approved,2026-01-01 13:20:55.530,Elena Santos
17,LOTE-M-SOP-008-8110,WO-5810,2026-01-01,ISBM-002,M-SOP-008,FR-008-PET-350,PET,Flash,Major,0.65,ISO 2859-1,II,9293,L,200,2,3,0,Approved,2026-01-01 14:27:51.488,Elena Santos
18,LOTE-M-SOP-008-8110,WO-5810,2026-01-01,ISBM-002,M-SOP-008,FR-008-PET-350,PET,Bubbles,Major,0.65,ISO 2859-1,II,9293,L,200,2,3,0,Approved,2026-01-01 15:40:05.385,Elena Santos
19,LOTE-M-SOP-008-8110,WO-5810,2026-01-01,ISBM-002,M-SOP-008,FR-008-PET-350,PET,Black Specks,Minor,1.50,ISO 2859-1,II,9293,L,200,10,11,0,Approved,2026-01-01 15:21:31.703,Elena Santos
20,LOTE-M-SOP-008-8110,WO-5810,2026-01-01,ISBM-002,M-SOP-008,FR-008-PET-350,PET,Stain,Minor,1.50,ISO 2859-1,II,9293,L,200,10,11,0,Approved,2026-01-01 13:39:13.051,Elena Santos
21,LOTE-M-SOP-008-8110,WO-5810,2026-01-01,ISBM-002,M-SOP-008,FR-008-PET-350,PET,Transparency,Minor,1.50,ISO 2859-1,II,9293,L,200,10,11,0,Approved,2026-01-01 15:06:51.096,Elena Santos
22,LOTE-M-SOP-008-8110,WO-5810,2026-01-01,ISBM-002,M-SOP-008,FR-008-PET-350,PET,Color,Minor,1.50,ISO 2859-1,II,9293,L,200,10,11,2,Approved,2026-01-01 15:45:39.811,Elena Santos
23,LOTE-M-SOP-008-8110,WO-5810,2026-01-01,ISBM-002,M-SOP-008,FR-008-PET-350,PET,Burr,Major,0.65,ISO 2859-1,II,9293,L,200,2,3,0,Approved,2026-01-01 16:31:05.804,Elena Santos
24,LOTE-M-SOP-008-8120,WO-5811,2026-01-01,ISBM-002,M-SOP-008,FR-008-PET-350,PET,Leakage,Critical,0.10,ISO 2859-1,II,11290,M,315,0,1,0,Approved,2026-01-02 08:55:52.102,Elena Santos
25,LOTE-M-SOP-008-8120,WO-5811,2026-01-01,ISBM-002,M-SOP-008,FR-008-PET-350,PET,Flash,Major,0.65,ISO 2859-1,II,11290,M,315,3,4,0,Approved,2026-01-02 15:24:45.769,Elena Santos
26,LOTE-M-SOP-008-8120,WO-5811,2026-01-01,ISBM-002,M-SOP-008,FR-008-PET-350,PET,Bubbles,Major,0.65,ISO 2859-1,II,11290,M,315,3,4,0,Approved,2026-01-02 11:59:01.421,Elena Santos
27,LOTE-M-SOP-008-8120,WO-5811,2026-01-01,ISBM-002,M-SOP-008,FR-008-PET-350,PET,Black Specks,Minor,1.50,ISO 2859-1,II,11290,M,315,14,15,0,Approved,2026-01-02 14:30:34.335,Elena Santos
28,LOTE-M-SOP-008-8120,WO-5811,2026-01-01,ISBM-002,M-SOP-008,FR-008-PET-350,PET,Stain,Minor,1.50,ISO 2859-1,II,11290,M,315,14,15,0,Approved,2026-01-02 07:38:44.333,Elena Santos
29,LOTE-M-SOP-008-8120,WO-5811,2026-01-01,ISBM-002,M-SOP-008,FR-008-PET-350,PET,Transparency,Minor,1.50,ISO 2859-1,II,11290,M,315,14,15,0,Approved,2026-01-02 09:28:47.919,Elena Santos

====================================================================================================
fact_bottle_disposition_lot_cq_raw -- first 30 rows
====================================================================================================

,ProductBatch,WorkOrder,ProductionDate,Shift,MachineId,MoldId,BottleId,LotSize,CodeLetter,SampleSize,CriticalDefects,MajorDefects,MinorDefects,TotalSampleDefects,VariablesDecision,AttributesDecision,FinalLotDecision,LotDecisionDateTime,Remarks,Inspector
0,LOTE-M-SOP-007-2950,WO-5294,2026-01-01,SHIFT 3,ISBM-001,M-SOP-007,FR-007-PP-350,3554,L,200,0,0,0,0,Conforming,Approved,Approved,2026-01-01 08:47:30.771,—,Beatriz Costa
1,LOTE-M-SOP-001-2960,WO-5295,2026-01-01,Shift 1,ISBM-001,M-SOP-001,FR-001-HDPE-300,10738,M,315,0,0,0,0,Nonconformance Detected,Approved,Approved,2026-01-02 04:30:04.667,—,Diogo Ferreira
2,LOTE-M-SOP-008-8110,WO-5810,2026-01-01,shift 3,ISBM-002,M-SOP-008,FR-008-PET-350,9293,L,200,0,0,0,0,Nonconformance Detected,Approved,Approved,2026-01-01 21:19:28.900,—,Elena Santos
3,LOTE-M-SOP-008-8120,WO-5811,2026-01-01,Shift 2,ISBM-002,M-SOP-008,FR-008-PET-350,11290,M,315,0,0,0,0,Nonconformance Detected,Approved,Approved,2026-01-02 17:48:03.332,—,Elena Santos
4,LOTE-M-SOP-009-3240,WO-6323,2026-01-01,Shift 3,ISBM-003,M-SOP-009,FR-009-HDPE-PCR-350,6622,L,200,0,0,0,0,Nonconformance Detected,Approved,Approved,2026-01-01 19:11:56.228,—,Ana Silva
5,LOTE-M-SOP-009-3250,WO-6324,2026-01-01,Shift 2,ISBM-003,M-SOP-009,FR-009-HDPE-PCR-350,4580,L,200,0,3,0,3,Conforming,Approved,Approved,2026-01-02 05:37:08.248,Flash:3(Re=3),Ana Silva
6,LOTE-M-SOP-029-8230,WO-6822,2026-01-01,Shift 2,ISBM-004,M-SOP-029,FR-029-MDPE-5000,476,H,50,0,0,0,0,Nonconformance Detected,Approved,Approved,2026-01-01 22:54:24.701,—,Beatriz Costa
7,LOTE-M-SOP-026-8240,WO-6823,2026-01-01,Shift 3,ISBM-004,M-SOP-026,FR-026-HDPE-4000,1625,K,125,0,0,0,0,Nonconformance Detected,Approved,Approved,2026-01-02 08:14:39.561,—,Ana Silva
8,LOTE-M-SOP-013-3230,WO-7322,2026-01-01,shift 1,ISBM-005,M-SOP-013,FR-013-LDPE-500,6578,L,200,0,0,0,0,Nonconformance Detected,Approved,Approved,2026-01-02 01:11:08.707,—,Beatriz Costa
9,LOTE-M-SOP-018-8340,WO-7833,2026-01-01,shift 1,ISBM-006,M-SOP-018,FR-018-PP-PCR-600,12594,M,315,0,0,0,0,Nonconformance Detected,Approved,Approved,2026-01-02 05:30:55.146,—,Elena Santos
10,LOTE-M-SOP-020-3410,WO-8340,2026-01-01,SHIFT 2,ISBM-007,M-SOP-020,FR-020-PET-750,9405,L,200,0,0,0,0,Nonconformance Detected,Approved,Approved,2026-01-02 14:33:41.568,—,Elena Santos
11,LOTE-M-SOP-022-8340,WO-8833,2026-01-01,Shift 1,ISBM-008,M-SOP-022,FR-022-MDPE-1000,8738,L,200,0,0,0,0,Nonconformance Detected,Approved,Approved,2026-01-02 05:32:05.282,—,Beatriz Costa
12,LOTE-M-SOP-001-2970,WO-5296,2026-01-02,shift 3,ISBM-001,M-SOP-001,FR-001-HDPE-PCR-300,12353,M,315,0,0,0,0,Nonconformance Detected,Approved,Approved,2026-01-03 01:47:51.145,—,Carlos Mendes
13,LOTE-M-SOP-008-8130,WO-5812,2026-01-02,Shift 2,ISBM-002,M-SOP-008,FR-008-PET-350,2879,K,125,0,0,0,0,Conforming,Approved,Approved,2026-01-02 22:35:48.809,—,Diogo Ferreira
14,LOTE-M-SOP-008-8140,WO-5813,2026-01-02,Shift 2,ISBM-002,M-SOP-008,FR-008-PET-350,6299,L,200,0,0,0,0,Conforming,Approved,Approved,2026-01-03 09:33:08.111,—,Ana Silva
15,LOTE-M-SOP-006-3260,WO-6325,2026-01-02,Shift 3,ISBM-003,M-SOP-006,FR-006-rPET-330,8293,L,200,0,4,0,4,Conforming,Rejected,Rejected,2026-01-03 02:13:52.302,Burr:4(Re=3),Carlos Mendes
16,LOTE-M-SOP-026-8250,WO-6824,2026-01-02,Shift 1,ISBM-004,M-SOP-026,FR-026-HDPE-4000,3800,L,200,0,0,0,0,Nonconformance Detected,Approved,Approved,2026-01-03 03:07:18.949,—,Carlos Mendes
17,LOTE-M-SOP-013-3240,WO-7323,2026-01-02,Shift 3,ISBM-005,M-SOP-013,FR-013-PVC-500,7674,L,200,0,0,0,0,Nonconformance Detected,Approved,Approved,2026-01-02 15:58:01.583,—,Elena Santos
18,LOTE-M-SOP-013-3250,WO-7324,2026-01-02,Shift 2,ISBM-005,M-SOP-013,FR-013-PP-500,4210,L,200,0,0,0,0,Nonconformance Detected,Approved,Approved,2026-01-03 00:23:39.698,—,Elena Santos
19,LOTE-M-SOP-013-3260,WO-7325,2026-01-02,Shift 3,ISBM-005,M-SOP-013,FR-013-PP-500,11913,M,315,0,0,0,0,Nonconformance Detected,Approved,Approved,2026-01-03 20:33:57.650,—,Beatriz Costa
20,LOTE-M-SOP-018-8350,WO-7834,2026-01-02,Shift 3,ISBM-006,M-SOP-018,FR-018-LDPE-600,7397,L,200,0,0,0,0,Nonconformance Detected,Approved,Approved,2026-01-02 17:11:42.538,—,Diogo Ferreira
21,LOTE-M-SOP-018-8360,WO-7835,2026-01-02,shift 2,ISBM-006,M-SOP-018,FR-018-LDPE-600,9616,L,200,0,0,0,0,Nonconformance Detected,Approved,Approved,2026-01-03 10:11:48.653,—,Ana Silva
22,LOTE-M-SOP-017-3420,WO-8341,2026-01-02,Shift 2,ISBM-007,M-SOP-017,FR-017-PP-600,6315,L,200,0,3,0,3,Nonconformance Detected,Approved,Approved,2026-01-03 02:09:19.905,Bubbles:3(Re=3),Ana Silva
23,LOTE-M-SOP-022-8350,WO-8834,2026-01-02,SHIFT 3,ISBM-008,M-SOP-022,FR-022-MDPE-1000,4842,L,200,0,0,0,0,Conforming,Approved,Approved,2026-01-02 16:20:00.677,—,Elena Santos
24,LOTE-M-SOP-019-8360,WO-8835,2026-01-02,Shift 2,ISBM-008,M-SOP-019,FR-019-PET-750,7703,L,200,0,0,0,0,Nonconformance Detected,Approved,Approved,2026-01-03 06:50:49.324,—,Elena Santos
25,LOTE-M-SOP-001-2980,WO-5297,2026-01-03,SHIFT 3,ISBM-001,M-SOP-001,FR-001-HDPE-PCR-300,4283,L,200,0,0,0,0,Nonconformance Detected,Approved,Approved,2026-01-03 09:00:55.201,—,Ana Silva
26,LOTE-M-SOP-001-2990,WO-5298,2026-01-03,Shift 1,ISBM-001,M-SOP-001,FR-001-HDPE-PCR-300,5762,L,200,0,0,0,0,Conforming,Approved,Approved,2026-01-03 18:20:59.103,—,Carlos Mendes
27,LOTE-M-SOP-007-3000,WO-5299,2026-01-03,Shift 2,ISBM-001,M-SOP-007,FR-007-PVC-350,2130,K,125,0,0,0,0,Conforming,Approved,Approved,2026-01-03 22:46:07.846,—,Elena Santos
28,LOTE-M-SOP-008-8150,WO-5814,2026-01-03,Shift 1,ISBM-002,M-SOP-008,FR-008-HDPE-PCR-350,5447,L,200,0,0,0,0,Nonconformance Detected,Approved,Approved,2026-01-03 19:35:07.533,—,Diogo Ferreira
29,LOTE-M-SOP-008-8160,WO-5815,2026-01-03,Shift 2,ISBM-002,M-SOP-008,FR-008-PP-PCR-350,1692,K,125,0,0,0,0,Conforming,Approved,Approved,2026-01-03 23:28:06.984,—,Ana Silva

====================================================================================================
fact_ink_attribute_inspection_cq_raw -- first 30 rows
====================================================================================================

,PrintLot,ProductBatch,WorkOrder,ProductionDate,Shift,MachineId,PrintToolId,BottleId,ColorCount,ColorsUsed,Characteristic,Class,AQL,Standard,InspectionLevel,Frequency,Equipment,LotSize,CodeLetter,SampleSize,AcceptanceNumber,RejectionNumber,DefectsFound,LotDecision,InspectionDateTime,Inspector
0,LOTE-SK-M-SOP-011-3240,LOTE-M-SOP-011-3240,WO-9323,2026-01-01,Shift 2,SS-001,SK-FR-011-PET-400-2C,FR-011-PET-400,2,"COR-006, COR-008",Registration,Critical,0.65,ISO 2859-1,II,Per lot,Registration Gauge,19128,M,315,3,4,0,Approved,2026-01-01 15:02:25.584,Elena Santos
1,LOTE-SK-M-SOP-011-3240,LOTE-M-SOP-011-3240,WO-9323,2026-01-01,shift 1,SS-001,SK-FR-011-PET-400-2C,FR-011-PET-400,2,"COR-006, COR-008",Centering,Critical,0.65,ISO 2859-1,II,Every 30 min,Registration Gauge,19128,M,315,3,4,1,Approved,2026-01-01 12:48:22.985,Elena Santos
2,LOTE-SK-M-SOP-011-3240,LOTE-M-SOP-011-3240,WO-9323,2026-01-01,Shift 1,SS-001,SK-FR-011-PET-400-2C,FR-011-PET-400,2,"COR-006, COR-008",Coverage,Major,0.65,ISO 2859-1,II,Every 30 min,D65 Light Booth,19128,M,315,3,4,0,Approved,2026-01-01 10:09:43.076,Elena Santos
3,LOTE-SK-M-SOP-011-3240,LOTE-M-SOP-011-3240,WO-9323,2026-01-01,Shift 2,SS-001,SK-FR-011-PET-400-2C,FR-011-PET-400,2,"COR-006, COR-008",Color,Minor,1.50,ISO 2859-1,II,Every 30 min,Colorimeter,19128,M,315,14,15,0,Approved,2026-01-01 21:21:34.005,Elena Santos
4,LOTE-SK-M-SOP-011-3240,LOTE-M-SOP-011-3240,WO-9323,2026-01-01,Shift 1,SS-001,SK-FR-011-PET-400-2C,FR-011-PET-400,2,"COR-006, COR-008",Smudge,Minor,1.50,ISO 2859-1,II,Continuous,D65 Light Booth,19128,M,315,14,15,0,Approved,2026-01-01 06:20:23.561,Elena Santos
5,LOTE-SK-M-SOP-011-3240,LOTE-M-SOP-011-3240,WO-9323,2026-01-01,shift 1,SS-001,SK-FR-011-PET-400-2C,FR-011-PET-400,2,"COR-006, COR-008",Pinholes,Minor,1.50,ISO 2859-1,II,Continuous,Lupa 10x,19128,M,315,14,15,0,Approved,2026-01-01 08:33:00.829,Elena Santos
6,LOTE-SK-M-SOP-011-3240,LOTE-M-SOP-011-3240,WO-9323,2026-01-01,Shift 1,SS-001,SK-FR-011-PET-400-2C,FR-011-PET-400,2,"COR-006, COR-008",Adhesion,Critical,0.10,ISO 2859-1,II,Per lot (fixed),ASTM D3359 Kit,19128,—,3,0,1,0,Approved,2026-01-01 07:10:31.124,Elena Santos
7,LOTE-SK-M-SOP-011-3240,LOTE-M-SOP-011-3240,WO-9323,2026-01-01,Shift 3,SS-001,SK-FR-011-PET-400-2C,FR-011-PET-400,2,"COR-006, COR-008",Cure,Critical,0.10,ISO 2859-1,II,Per lot (fixed),MEK Rub Test,19128,—,3,0,1,0,Approved,2026-01-01 04:05:06.730,Elena Santos
8,LOTE-SK-M-SOP-013-8350,LOTE-M-SOP-013-8350,WO-9834,2026-01-01,Shift 1,SS-002,SK-FR-013-MDPE-500-2C,FR-013-MDPE-500,2,"COR-002, COR-005",Registration,Critical,0.65,ISO 2859-1,II,Per lot,Registration Gauge,7562,L,200,2,3,0,Approved,2026-01-01 11:00:21.829,Ana Silva
9,LOTE-SK-M-SOP-013-8350,LOTE-M-SOP-013-8350,WO-9834,2026-01-01,Shift 1,SS-002,SK-FR-013-MDPE-500-2C,FR-013-MDPE-500,2,"COR-002, COR-005",Centering,Critical,0.65,ISO 2859-1,II,Every 30 min,Registration Gauge,7562,L,200,2,3,0,Approved,2026-01-01 11:06:54.650,Ana Silva
10,LOTE-SK-M-SOP-013-8350,LOTE-M-SOP-013-8350,WO-9834,2026-01-01,Shift 1,SS-002,SK-FR-013-MDPE-500-2C,FR-013-MDPE-500,2,"COR-002, COR-005",Coverage,Major,0.65,ISO 2859-1,II,Every 30 min,D65 Light Booth,7562,L,200,2,3,0,Approved,2026-01-01 11:49:25.258,Ana Silva
11,LOTE-SK-M-SOP-013-8350,LOTE-M-SOP-013-8350,WO-9834,2026-01-01,Shift 2,SS-002,SK-FR-013-MDPE-500-2C,FR-013-MDPE-500,2,"COR-002, COR-005",Color,Minor,1.50,ISO 2859-1,II,Every 30 min,Colorimeter,7562,L,200,10,11,6,Approved,2026-01-01 14:33:20.467,Ana Silva
12,LOTE-SK-M-SOP-013-8350,LOTE-M-SOP-013-8350,WO-9834,2026-01-01,Shift 1,SS-002,SK-FR-013-MDPE-500-2C,FR-013-MDPE-500,2,"COR-002, COR-005",Smudge,Minor,1.50,ISO 2859-1,II,Continuous,D65 Light Booth,7562,L,200,10,11,1,Approved,2026-01-01 11:18:24.833,Ana Silva
13,LOTE-SK-M-SOP-013-8350,LOTE-M-SOP-013-8350,WO-9834,2026-01-01,Shift 1,SS-002,SK-FR-013-MDPE-500-2C,FR-013-MDPE-500,2,"COR-002, COR-005",Pinholes,Minor,1.50,ISO 2859-1,II,Continuous,Lupa 10x,7562,L,200,10,11,0,Approved,2026-01-01 11:56:47.153,Ana Silva
14,LOTE-SK-M-SOP-013-8350,LOTE-M-SOP-013-8350,WO-9834,2026-01-01,Shift 1,SS-002,SK-FR-013-MDPE-500-2C,FR-013-MDPE-500,2,"COR-002, COR-005",Adhesion,Critical,0.10,ISO 2859-1,II,Per lot (fixed),ASTM D3359 Kit,7562,—,3,0,1,0,Approved,2026-01-01 13:42:30.422,Ana Silva
15,LOTE-SK-M-SOP-013-8350,LOTE-M-SOP-013-8350,WO-9834,2026-01-01,Shift 1,SS-002,SK-FR-013-MDPE-500-2C,FR-013-MDPE-500,2,"COR-002, COR-005",Cure,Critical,0.10,ISO 2859-1,II,Per lot (fixed),MEK Rub Test,7562,—,3,0,1,0,Approved,2026-01-01 08:56:33.942,Ana Silva
16,LOTE-SK-M-SOP-009-8360,LOTE-M-SOP-009-8360,WO-9835,2026-01-01,Shift 3,SS-002,SK-FR-009-PET-350-1C,FR-009-PET-350,1,COR-008,Registration,Critical,0.65,ISO 2859-1,II,Per lot,Registration Gauge,16871,M,315,3,4,0,Approved,2026-01-02 00:38:53.410,Diogo Ferreira
17,LOTE-SK-M-SOP-009-8360,LOTE-M-SOP-009-8360,WO-9835,2026-01-01,Shift 3,SS-002,SK-FR-009-PET-350-1C,FR-009-PET-350,1,COR-008,Centering,Critical,0.65,ISO 2859-1,II,Every 30 min,Registration Gauge,16871,M,315,3,4,1,Approved,2026-01-01 23:03:33.082,Diogo Ferreira
18,LOTE-SK-M-SOP-009-8360,LOTE-M-SOP-009-8360,WO-9835,2026-01-01,Shift 1,SS-002,SK-FR-009-PET-350-1C,FR-009-PET-350,1,COR-008,Coverage,Major,0.65,ISO 2859-1,II,Every 30 min,D65 Light Booth,16871,M,315,3,4,1,Approved,2026-01-02 08:07:52.123,Diogo Ferreira
19,LOTE-SK-M-SOP-009-8360,LOTE-M-SOP-009-8360,WO-9835,2026-01-01,Shift 3,SS-002,SK-FR-009-PET-350-1C,FR-009-PET-350,1,COR-008,Color,Minor,1.50,ISO 2859-1,II,Every 30 min,Colorimeter,16871,M,315,14,15,0,Approved,2026-01-01 22:56:56.084,Diogo Ferreira
20,LOTE-SK-M-SOP-009-8360,LOTE-M-SOP-009-8360,WO-9835,2026-01-01,Shift 3,SS-002,SK-FR-009-PET-350-1C,FR-009-PET-350,1,COR-008,Smudge,Minor,1.50,ISO 2859-1,II,Continuous,D65 Light Booth,16871,M,315,14,15,1,Approved,2026-01-01 22:16:27.295,Diogo Ferreira
21,LOTE-SK-M-SOP-009-8360,LOTE-M-SOP-009-8360,WO-9835,2026-01-01,Shift 3,SS-002,SK-FR-009-PET-350-1C,FR-009-PET-350,1,COR-008,Pinholes,Minor,1.50,ISO 2859-1,II,Continuous,Lupa 10x,16871,M,315,14,15,1,Approved,2026-01-02 00:11:12.855,Diogo Ferreira
22,LOTE-SK-M-SOP-009-8360,LOTE-M-SOP-009-8360,WO-9835,2026-01-01,Shift 2,SS-002,SK-FR-009-PET-350-1C,FR-009-PET-350,1,COR-008,Adhesion,Critical,0.10,ISO 2859-1,II,Per lot (fixed),ASTM D3359 Kit,16871,—,3,0,1,0,Approved,2026-01-01 19:35:01.421,Diogo Ferreira
23,LOTE-SK-M-SOP-009-8360,LOTE-M-SOP-009-8360,WO-9835,2026-01-01,Shift 3,SS-002,SK-FR-009-PET-350-1C,FR-009-PET-350,1,COR-008,Cure,Critical,0.10,ISO 2859-1,II,Per lot (fixed),MEK Rub Test,16871,—,3,0,1,0,Approved,2026-01-02 01:04:06.892,Diogo Ferreira
24,LOTE-SK-M-SOP-004-3250,LOTE-M-SOP-004-3250,WO-9324,2026-01-02,SHIFT 2,SS-001,SK-FR-004-rPET-330-1C,FR-004-rPET-330,1,COR-008,Registration,Critical,0.65,ISO 2859-1,II,Per lot,Registration Gauge,18754,M,315,3,4,0,Approved,2026-01-02 14:53:49.672,Beatriz Costa
25,LOTE-SK-M-SOP-004-3250,LOTE-M-SOP-004-3250,WO-9324,2026-01-02,Shift 3,SS-001,SK-FR-004-rPET-330-1C,FR-004-rPET-330,1,COR-008,Centering,Critical,0.65,ISO 2859-1,II,Every 30 min,Registration Gauge,18754,M,315,3,4,0,Approved,2026-01-02 03:54:48.864,Beatriz Costa
26,LOTE-SK-M-SOP-004-3250,LOTE-M-SOP-004-3250,WO-9324,2026-01-02,Shift 1,SS-001,SK-FR-004-rPET-330-1C,FR-004-rPET-330,1,COR-008,Coverage,Major,0.65,ISO 2859-1,II,Every 30 min,D65 Light Booth,18754,M,315,3,4,1,Approved,2026-01-02 13:10:05.430,Beatriz Costa
27,LOTE-SK-M-SOP-004-3250,LOTE-M-SOP-004-3250,WO-9324,2026-01-02,Shift 2,SS-001,SK-FR-004-rPET-330-1C,FR-004-rPET-330,1,COR-008,Color,Minor,1.50,ISO 2859-1,II,Every 30 min,Colorimeter,18754,M,315,14,15,0,Approved,2026-01-02 14:34:52.795,Beatriz Costa
28,LOTE-SK-M-SOP-004-3250,LOTE-M-SOP-004-3250,WO-9324,2026-01-02,Shift 1,SS-001,SK-FR-004-rPET-330-1C,FR-004-rPET-330,1,COR-008,Smudge,Minor,1.50,ISO 2859-1,II,Continuous,D65 Light Booth,18754,M,315,14,15,1,Approved,2026-01-02 12:42:47.727,Beatriz Costa
29,LOTE-SK-M-SOP-004-3250,LOTE-M-SOP-004-3250,WO-9324,2026-01-02,Shift 1,SS-001,SK-FR-004-rPET-330-1C,FR-004-rPET-330,1,COR-008,Pinholes,Minor,1.50,ISO 2859-1,II,Continuous,Lupa 10x,18754,M,315,14,15,1,Approved,2026-01-02 12:30:48.932,Beatriz Costa

====================================================================================================
fact_ink_disposition_lot_cq_raw -- first 30 rows
====================================================================================================

,PrintLot,BottleLot,WorkOrder,ProductionDate,Shift,MachineId,PrintToolId,BottleId,ColorCount,ColorsUsed,LotSize,CodeLetter,SampleSize,CriticalDefects,MajorDefects,MinorDefects,TotalSampleDefects,AttributesDecision,FinalLotDecision,LotDecisionDateTime,Remarks,Inspector
0,LOTE-SK-M-SOP-011-3240,LOTE-M-SOP-011-3240,WO-9323,2026-01-01,Shift 3,SS-001,SK-FR-011-PET-400-2C,FR-011-PET-400,2,"COR-006, COR-008",19128,M,315,0,0,0,0,Approved,Approved,2026-01-02 00:09:57.057,—,Elena Santos
1,LOTE-SK-M-SOP-013-8350,LOTE-M-SOP-013-8350,WO-9834,2026-01-01,Shift 1,SS-002,SK-FR-013-MDPE-500-2C,FR-013-MDPE-500,2,"COR-002, COR-005",7562,L,200,0,0,0,0,Approved,Approved,2026-01-01 16:22:39.174,—,Ana Silva
2,LOTE-SK-M-SOP-009-8360,LOTE-M-SOP-009-8360,WO-9835,2026-01-01,Shift 2,SS-002,SK-FR-009-PET-350-1C,FR-009-PET-350,1,COR-008,16871,M,315,0,0,0,0,Approved,Approved,2026-01-02 12:27:20.726,—,Diogo Ferreira
3,LOTE-SK-M-SOP-004-3250,LOTE-M-SOP-004-3250,WO-9324,2026-01-02,SHIFT 3,SS-001,SK-FR-004-rPET-330-1C,FR-004-rPET-330,1,COR-008,18754,M,315,0,0,0,0,Approved,Approved,2026-01-02 21:38:13.807,—,Beatriz Costa
4,LOTE-SK-M-SOP-004-3260,LOTE-M-SOP-004-3260,WO-9325,2026-01-02,Shift 2,SS-001,SK-FR-004-rPET-330-1C,FR-004-rPET-330,1,COR-008,8428,L,200,0,0,0,0,Approved,Approved,2026-01-03 06:30:26.901,—,Elena Santos
5,LOTE-SK-M-SOP-009-8370,LOTE-M-SOP-009-8370,WO-9836,2026-01-02,Shift 1,SS-002,SK-FR-009-PET-350-1C,FR-009-PET-350,1,COR-008,18243,M,315,0,0,0,0,Approved,Approved,2026-01-03 09:47:44.851,—,Elena Santos
6,LOTE-SK-M-SOP-004-3270,LOTE-M-SOP-004-3270,WO-9326,2026-01-03,Shift 3,SS-001,SK-FR-004-rPET-330-1C,FR-004-rPET-330,1,COR-008,6660,L,200,0,0,0,0,Approved,Approved,2026-01-03 13:29:01.577,—,Carlos Mendes
7,LOTE-SK-M-SOP-014-3280,LOTE-M-SOP-014-3280,WO-9327,2026-01-03,Shift 1,SS-001,SK-FR-014-PETG-500-3C,FR-014-PETG-500,3,"COR-006, COR-008",7556,L,200,0,0,0,0,Approved,Approved,2026-01-03 22:55:52.367,—,Carlos Mendes
8,LOTE-SK-M-SOP-007-8380,LOTE-M-SOP-007-8380,WO-9837,2026-01-03,Shift 1,SS-002,SK-FR-007-HDPE-PCR-350-2C,FR-007-HDPE-PCR-350,2,"COR-002, COR-003",10917,M,315,0,0,0,0,Approved,Approved,2026-01-03 22:26:23.830,—,Beatriz Costa
9,LOTE-SK-M-SOP-014-3290,LOTE-M-SOP-014-3290,WO-9328,2026-01-05,Shift 1,SS-001,SK-FR-014-PETG-500-3C,FR-014-PETG-500,3,"COR-002, COR-008",6738,L,200,0,0,0,0,Approved,Approved,2026-01-05 14:51:06.096,—,Carlos Mendes
10,LOTE-SK-M-SOP-014-3300,LOTE-M-SOP-014-3300,WO-9329,2026-01-05,Shift 1,SS-001,SK-FR-014-PETG-500-3C,FR-014-PETG-500,3,"COR-005, COR-006, COR-008",11626,M,315,0,0,0,0,Approved,Approved,2026-01-06 03:11:30.121,—,Carlos Mendes
11,LOTE-SK-M-SOP-018-8390,LOTE-M-SOP-018-8390,WO-9838,2026-01-05,Shift 1,SS-002,SK-FR-018-PP-600-2C,FR-018-PP-600,2,"COR-001, COR-007",18074,M,315,0,0,0,0,Approved,Approved,2026-01-06 05:03:22.978,—,Elena Santos
12,LOTE-SK-M-SOP-014-3310,LOTE-M-SOP-014-3310,WO-9330,2026-01-06,Shift 3,SS-001,SK-FR-014-PETG-500-3C,FR-014-PETG-500,3,"COR-004, COR-005, COR-008",4987,L,200,0,0,0,0,Approved,Approved,2026-01-06 08:58:37.584,—,Ana Silva
13,LOTE-SK-M-SOP-014-3320,LOTE-M-SOP-014-3320,WO-9331,2026-01-06,Shift 1,SS-001,SK-FR-014-PETG-500-3C,FR-014-PETG-500,3,"COR-004, COR-007, COR-008",9969,L,200,0,0,0,0,Approved,Approved,2026-01-06 19:38:23.246,—,Beatriz Costa
14,LOTE-SK-M-SOP-009-3330,LOTE-M-SOP-009-3330,WO-9332,2026-01-06,Shift 2,SS-001,SK-FR-009-rPET-350-1C,FR-009-rPET-350,1,COR-008,8813,L,200,0,0,0,0,Approved,Approved,2026-01-07 05:55:23.234,—,Ana Silva
15,LOTE-SK-M-SOP-018-8400,LOTE-M-SOP-018-8400,WO-9839,2026-01-06,SHIFT 3,SS-002,SK-FR-018-PP-600-2C,FR-018-PP-600,2,"COR-001, COR-008",11727,M,315,0,0,0,0,Approved,Approved,2026-01-06 18:08:23.760,—,Carlos Mendes
16,LOTE-SK-M-SOP-018-8410,LOTE-M-SOP-018-8410,WO-9840,2026-01-06,Shift 2,SS-002,SK-FR-018-PP-600-2C,FR-018-PP-600,2,"COR-001, COR-002",16088,M,315,0,0,0,0,Approved,Approved,2026-01-07 14:47:11.948,—,Ana Silva
17,LOTE-SK-M-SOP-009-3340,LOTE-M-SOP-009-3340,WO-9333,2026-01-07,Shift 3,SS-001,SK-FR-009-rPET-350-1C,FR-009-rPET-350,1,COR-008,6552,L,200,0,0,0,0,Approved,Approved,2026-01-07 13:23:17.367,—,Beatriz Costa
18,LOTE-SK-M-SOP-022-3350,LOTE-M-SOP-022-3350,WO-9334,2026-01-07,Shift 1,SS-001,SK-FR-022-PP-PCR-1000-3C,FR-022-PP-PCR-1000,3,"COR-003, COR-004, COR-005",5753,L,200,0,0,0,0,Approved,Approved,2026-01-07 20:11:04.461,—,Ana Silva
19,LOTE-SK-M-SOP-022-3360,LOTE-M-SOP-022-3360,WO-9335,2026-01-07,Shift 2,SS-001,SK-FR-022-PP-PCR-1000-3C,FR-022-PP-PCR-1000,3,"COR-003, COR-008",5070,L,200,0,0,0,0,Approved,Approved,2026-01-08 01:30:33.760,—,Beatriz Costa
20,LOTE-SK-M-SOP-016-8420,LOTE-M-SOP-016-8420,WO-9841,2026-01-07,Shift 1,SS-002,SK-FR-016-HDPE-600-3C,FR-016-HDPE-600,3,"COR-001, COR-002",8304,L,200,0,0,0,0,Approved,Approved,2026-01-08 00:09:38.295,—,Ana Silva
21,LOTE-SK-M-SOP-019-8430,LOTE-M-SOP-019-8430,WO-9842,2026-01-07,Shift 3,SS-002,SK-FR-019-rPET-600-2C,FR-019-rPET-600,2,"COR-001, COR-008",5624,L,200,0,0,0,0,Approved,Approved,2026-01-08 06:58:06.953,—,Elena Santos
22,LOTE-SK-M-SOP-022-3370,LOTE-M-SOP-022-3370,WO-9336,2026-01-08,shift 3,SS-001,SK-FR-022-PP-PCR-1000-3C,FR-022-PP-PCR-1000,3,"COR-002, COR-003, COR-005",16727,M,315,0,0,0,0,Approved,Approved,2026-01-08 20:10:38.053,—,Elena Santos
23,LOTE-SK-M-SOP-008-3380,LOTE-M-SOP-008-3380,WO-9337,2026-01-08,Shift 2,SS-001,SK-FR-008-HDPE-PCR-350-1C,FR-008-HDPE-PCR-350,1,COR-003,16295,M,315,0,0,0,0,Approved,Approved,2026-01-09 14:11:03.461,—,Ana Silva
24,LOTE-SK-M-SOP-021-8440,LOTE-M-SOP-021-8440,WO-9843,2026-01-08,Shift 1,SS-002,SK-FR-021-rPET-750-2C,FR-021-rPET-750,2,"COR-001, COR-008",6011,L,200,0,0,0,0,Approved,Approved,2026-01-08 14:52:53.120,—,Elena Santos
25,LOTE-SK-M-SOP-018-8450,LOTE-M-SOP-018-8450,WO-9844,2026-01-08,Shift 2,SS-002,SK-FR-018-LDPE-600-2C,FR-018-LDPE-600,2,"COR-001, COR-007",10322,M,315,0,0,0,0,Approved,Approved,2026-01-09 03:42:30.293,—,Beatriz Costa
26,LOTE-SK-M-SOP-008-3390,LOTE-M-SOP-008-3390,WO-9338,2026-01-09,SHIFT 1,SS-001,SK-FR-008-HDPE-PCR-350-1C,FR-008-HDPE-PCR-350,1,COR-003,14711,M,315,0,0,0,0,Approved,Approved,2026-01-10 07:08:00.839,—,Carlos Mendes
27,LOTE-SK-M-SOP-018-8460,LOTE-M-SOP-018-8460,WO-9845,2026-01-09,SHIFT 3,SS-002,SK-FR-018-HDPE-PCR-600-2C,FR-018-HDPE-PCR-600,2,"COR-005, COR-006",14164,M,315,0,0,0,0,Approved,Approved,2026-01-09 21:43:33.716,—,Carlos Mendes
28,LOTE-SK-M-SOP-018-8470,LOTE-M-SOP-018-8470,WO-9846,2026-01-09,shift 2,SS-002,SK-FR-018-HDPE-PCR-600-2C,FR-018-HDPE-PCR-600,2,"COR-005, COR-007",8377,L,200,0,0,0,0,Approved,Approved,2026-01-10 07:11:19.600,—,Ana Silva
29,LOTE-SK-M-SOP-008-3400,LOTE-M-SOP-008-3400,WO-9339,2026-01-12,Shift 1,SS-001,SK-FR-008-HDPE-PCR-350-1C,FR-008-HDPE-PCR-350,1,COR-003,6765,L,200,0,0,0,0,Approved,Approved,2026-01-12 14:28:03.803,—,Beatriz Costa

In [9]:
for name, df in cq_tables.items():
    nulls = df.isna().sum()
    nulls = nulls[nulls > 0]
    print(f"{name}: {len(df):,} rows, {nulls.sum():,} missing values across {len(nulls)} columns")

fact_cap_inspection_variable_cq_raw: 83,947 rows, 8,270 missing values across 5 columns
fact_cap_attribute_inspection_cq_raw: 9,924 rows, 0 missing values across 0 columns
fact_cap_disposition_lot_cq_raw: 1,654 rows, 0 missing values across 0 columns

fact_bottle_inspection_variables_cq_raw: 124,580 rows, 4,380 missing values across 2 columns
fact_bottle_attribute_inspection_cq_raw: 17,520 rows, 0 missing values across 0 columns
fact_bottle_disposition_lot_cq_raw: 2,190 rows, 0 missing values across 0 columns
fact_ink_attribute_inspection_cq_raw: 4,456 rows, 0 missing values across 0 columns
fact_ink_disposition_lot_cq_raw: 557 rows, 0 missing values across 0 columns

## 3. Dimension / master-data tables

Governed reference data (machine capacities, cap/bottle specifications,
control plans). These come from engineering, not the shop floor, so we
expect -- and will verify -- that they arrive much cleaner than the fact
tables.

In [10]:
dim_files = {
    'dim_masterbatch': f'{DIM}/dim_masterbatch.csv',
    'dim_machine_setup': f'{DIM}/dim_machine_setup.csv',
    'dim_cap': f'{DIM}/dim_cap.csv',
    'dim_cap_control_plan_cq': f'{DIM}/dim_cap_control_plan_cq.csv',
    'dim_bottle_control_plan_cq': f'{DIM}/dim_bottle_control_plan_cq.csv',
    'dim_ink_control_plan_cq': f'{DIM}/dim_ink_control_plan_cq.csv',
}
dim_tables = {name: pd.read_csv(path, encoding='utf-8-sig') for name, path in dim_files.items()}
for name, df in dim_tables.items():
    print(f"{name}: {df.shape[0]:,} rows x {df.shape[1]} columns, "
          f"{int(df.isna().sum().sum())} missing values")
    display(df.head(10))

dim_masterbatch: 132 rows x 9 columns, 0 missing values

             ProductId ProductType     MoldId BaseMaterial  ColorId            ColorName     PantoneCodeApprox    MasterbatchType  StandardDosagePctMass
0      FR-001-HDPE-300      Bottle  M-SOP-001         HDPE  COR-007         Cardinal Red         Pantone 200 C    Red Masterbatch                  0.020
1  FR-002-HDPE-PCR-300      Bottle  M-SOP-002     HDPE-PCR  COR-003          Cobalt Blue        Pantone 2145 C   Blue Masterbatch                  0.020
2  FR-001-HDPE-PCR-300      Bottle  M-SOP-001     HDPE-PCR  COR-007         Cardinal Red         Pantone 200 C    Red Masterbatch                  0.020
3      FR-001-rPET-300      Bottle  M-SOP-001         rPET  COR-008  Natural (Uncolored)                     —     No Masterbatch                  0.000
4      FR-003-rPET-300      Bottle  M-SOP-003         rPET  COR-008  Natural (Uncolored)                     —     No Masterbatch                  0.000
5      FR-004-rPET-330      Bottle  M-SOP-004         rPET  COR-008  Natural (Uncolored)                     —     No Masterbatch                  0.000
6      FR-008-HDPE-350      Bottle  M-SOP-008         HDPE  COR-006        Graphite Gray  Pantone Cool Gray 11   Gray Masterbatch                  0.020
7      FR-007-HDPE-350      Bottle  M-SOP-007         HDPE  COR-005    Translucent Amber        Pantone 1375 C  Amber Masterbatch                  0.015
8      FR-009-HDPE-350      Bottle  M-SOP-009         HDPE  COR-007         Cardinal Red         Pantone 200 C    Red Masterbatch                  0.020
9  FR-008-HDPE-PCR-350      Bottle  M-SOP-008     HDPE-PCR  COR-003          Cobalt Blue        Pantone 2145 C   Blue Masterbatch                  0.020

dim_machine_setup: 38 rows x 8 columns, 0 missing values

      MoldId MachineId                   Product  Cavities  RatedCapacityPerDay RatedCapacityPerHour  CyclesPerHour  IdealCycleTimeSec
0  M-INJ-001    IM-001  Tampa rosca comum 24/410        24   ~28.800 pieces/day       ~1200 pieces/h             50                 72
1  M-INJ-002    IM-002  Tampa rosca comum 24/410        16   ~19.200 pieces/day        ~800 pieces/h             50                 72
2  M-INJ-003    IM-003  Tampa rosca comum 24/415        32   ~38.400 pieces/day       ~1600 pieces/h             50                 72
3  M-INJ-004    IM-004  Tampa rosca comum 28/410        24   ~28.800 pieces/day       ~1200 pieces/h             50                 72
4  M-INJ-005    IM-005     Tampa flip top 24/410        16   ~19.200 pieces/day        ~800 pieces/h             50                 72
5  M-INJ-009    IM-006     Tampa flip top 28/415        12   ~14.400 pieces/day        ~600 pieces/h             50                 72
6  M-INJ-006    IM-006     Tampa flip top 24/415         8    ~9.600 pieces/day        ~400 pieces/h             50                 72
7  M-INJ-007    IM-004     Tampa flip top 28/410        12   ~14.400 pieces/day        ~600 pieces/h             50                 72
8  M-INJ-008    IM-005     Tampa flip top 28/410        16   ~19.200 pieces/day        ~800 pieces/h             50                 72
9  M-SOP-001  ISBM-001      Frasco Round, 300 ml         8  ~14.400 bottles/day       ~600 bottles/h             75                 48

dim_cap: 31 rows x 15 columns, 0 missing values

,CapId,ItemDescription,OpeningType,MoldId,OuterDiameterMm,HeightMm,Material,MinWeightG,MaxWeightG,MinThicknessMm,MaxThicknessMm,ThreadType,ThreadDiameterMm,FiodaRosca,ThreadFinish
0,TR-001-HDPE-24410,Tampa rosca comum 24/410 HDPE,Screw Cap,M-INJ-001,29,18,HDPE,9.8,13.2,0.8,1.3,Screw Neck,24,410,24/410
1,TR-001-PP-24410,Tampa rosca comum 24/410 PP,Screw Cap,M-INJ-001,29,18,PP,8.6,12.1,0.8,1.3,Screw Neck,24,410,24/410
2,TR-001-PP-PCR-24410,Tampa rosca comum 24/410 PP-PCR,Screw Cap,M-INJ-001,29,18,PP-PCR,8.6,12.1,0.8,1.3,Screw Neck,24,410,24/410
3,TR-001-PETG-24410,Tampa rosca comum 24/410 PETG,Screw Cap,M-INJ-001,29,18,PETG,10.3,13.8,0.8,1.3,Screw Neck,24,410,24/410
4,TR-002-HDPE-24410,Tampa rosca comum 24/410 HDPE,Screw Cap,M-INJ-002,29,18,HDPE,9.8,13.2,0.8,1.3,Screw Neck,24,410,24/410
5,TR-002-PP-24410,Tampa rosca comum 24/410 PP,Screw Cap,M-INJ-002,29,18,PP,8.6,12.1,0.8,1.3,Screw Neck,24,410,24/410
6,TR-002-PP-PCR-24410,Tampa rosca comum 24/410 PP-PCR,Screw Cap,M-INJ-002,29,18,PP-PCR,8.6,12.1,0.8,1.3,Screw Neck,24,410,24/410
7,TR-002-PETG-24410,Tampa rosca comum 24/410 PETG,Screw Cap,M-INJ-002,29,18,PETG,10.3,13.8,0.8,1.3,Screw Neck,24,410,24/410
8,TR-003-HDPE-24415,Tampa rosca comum 24/415 HDPE,Screw Cap,M-INJ-003,29,18,HDPE,9.8,13.2,0.8,1.3,Screw Neck,24,415,24/415
9,TR-003-PP-24415,Tampa rosca comum 24/415 PP,Screw Cap,M-INJ-003,29,18,PP,8.6,12.1,0.8,1.3,Screw Neck,24,415,24/415

dim_cap_control_plan_cq: 10 rows x 19 columns, 0 missing values

,Process,Operation,Characteristic,Class,InspectionType,Specification,Method,Equipment,Standard,ISOLevel,AQL,Frequency,LotSize,ISOCode,SampleSize,AcceptanceNumber,RejectionNumber,Owner,ReactionPlan
0,Injection Molding,Production,Weight,Major,Variable,Per technical data sheet,Weighing,Scale 0.001 g,ISO 3951,—,—,Every 30 min,Production run,—,10 pieces,—,—,Quality,Adjust Process
1,Injection Molding,Production,Height,Major,Variable,Per drawing,Caliper,Caliper,ISO 3951,—,—,Every 1 h,Production run,—,10 pieces,—,—,Quality,Adjust Mold
2,Injection Molding,Production,Diameter,Major,Variable,Per drawing,Caliper,Caliper,ISO 3951,—,—,Every 1 h,Production run,—,10 pieces,—,—,Quality,Adjust Mold
3,Injection Molding,Production,Torque,Critical,Variable,Per specification,Torque Test,Torque Wrench,ISO 3951,—,—,Per lot,Lot,—,5 pieces,—,—,Laboratory,Adjust Mold
4,Injection Molding,Production,Thread,Critical,Attribute,Per drawing,Go/No-Go,Gauge,ISO 2859-1,II,0.1,Per lot,Per lot,Auto,Auto,0,1,Quality,Block Lot
5,Injection Molding,Production,Sealing,Critical,Attribute,No leakage,Leak Test,Leak Tester,ISO 2859-1,II,0.1,Per lot,Per lot,Auto,Auto,0,1,Laboratory,Block Lot
6,Injection Molding,Production,Flash,Major,Attribute,Absent,Visual,D65 Light Booth,ISO 2859-1,II,0.65,Every 30 min,Per lot,Auto,Auto,ver tabela,ver tabela,Operator,Adjust Machine
7,Injection Molding,Production,Short Shot,Major,Attribute,Absent,Visual,D65 Light Booth,ISO 2859-1,II,0.65,Every 30 min,Per lot,Auto,Auto,ver tabela,ver tabela,Operator,Adjust Pressure
8,Injection Molding,Production,Stain,Minor,Attribute,Absent,Visual,D65 Light Booth,ISO 2859-1,II,1.5,Every 30 min,Per lot,Auto,Auto,ver tabela,ver tabela,Operator,Adjust Process
9,Injection Molding,Production,Color,Minor,Attribute,Standard,Visual,D65 Light Booth,ISO 2859-1,II,1.5,Every 30 min,Per lot,Auto,Auto,ver tabela,ver tabela,Quality,Change Masterbatch Lot

dim_bottle_control_plan_cq: 13 rows x 19 columns, 0 missing values

,Process,Operation,Characteristic,Class,InspectionType,Specification,Method,Equipment,Standard,ISOLevel,AQL,Frequency,LotSize,ISOCode,SampleSize,AcceptanceNumber,RejectionNumber,Owner,ReactionPlan
0,Blow Molding,Production,Weight,Major,Variable,Per technical data sheet,Weighing,Scale 0.01 g,ISO 3951,—,—,Every 30 min,Production run (30min),—,5 pieces,—,—,Quality,Adjust Parameters
1,Blow Molding,Production,Height,Major,Variable,Per drawing,Caliper,Caliper,ISO 3951,—,—,Every 1 h,Production run (1h),—,5 pieces,—,—,Quality,Adjust Mold
2,Blow Molding,Production,Neck Diameter,Critical,Variable,Per drawing,Go/No-Go,Gauge,ISO 3951,—,—,Every 1 h,Production run (1h),—,5 pieces,—,—,Quality,Block Lot
3,Blow Molding,Production,Thickness,Major,Variable,Per technical data sheet,Ultrasound,Thickness Gauge,ISO 3951,—,—,Every 2 h,Production run (2h),—,5 pieces,—,—,Quality,Adjust Process
4,Blow Molding,Production,Overflow Volume,Major,Variable,Per technical data sheet,Fill Test,Graduated Cylinder,ISO 3951,—,—,Per lot,Lot,—,3 pieces,—,—,Laboratory,Block Lot
5,Blow Molding,Production,Leakage,Critical,Attribute,No leakage,Leak Test,Leak Tester,ISO 2859-1,II,0.1,Per lot,Per lot,Auto,Auto,0,1,Laboratory,Block Lot
6,Blow Molding,Production,Flash,Major,Attribute,Absent,Visual,D65 Light Booth,ISO 2859-1,II,0.65,Every 30 min,Per lot,Auto,Auto,ver tabela,ver tabela,Operator,Adjust Mold
7,Blow Molding,Production,Bubbles,Major,Attribute,Absent,Visual,D65 Light Booth,ISO 2859-1,II,0.65,Every 30 min,Per lot,Auto,Auto,ver tabela,ver tabela,Operator,Segregate
8,Blow Molding,Production,Black Specks,Minor,Attribute,≤1 per piece,Visual,D65 Light Booth,ISO 2859-1,II,1.5,Every 30 min,Per lot,Auto,Auto,ver tabela,ver tabela,Operator,Adjust Cleaning
9,Blow Molding,Production,Stain,Minor,Attribute,Absent,Visual,D65 Light Booth,ISO 2859-1,II,1.5,Every 30 min,Per lot,Auto,Auto,ver tabela,ver tabela,Operator,Adjust Process

dim_ink_control_plan_cq: 8 rows x 19 columns, 0 missing values

,Process,Operation,Characteristic,Class,InspectionType,Specification,Method,Equipment,Standard,ISOLevel,AQL,Frequency,LotSize,ISOCode,SampleSize,AcceptanceNumber,RejectionNumber,Owner,ReactionPlan
0,Screen Printing,Production,Registration,Critical,Attribute,Position per gauge,Visual,Registration Gauge,ISO 2859-1,II,0.65,Setup + 30 min,Per lot,Auto,Auto,ver tabela,ver tabela,Operator,Adjust Screen
1,Screen Printing,Production,Centering,Critical,Attribute,Centered ±1 mm,Visual,Registration Gauge,ISO 2859-1,II,0.65,Every 30 min,Per lot,Auto,Auto,ver tabela,ver tabela,Operator,Adjust Registration
2,Screen Printing,Production,Coverage,Major,Attribute,100% printed area,Visual,D65 Light Booth,ISO 2859-1,II,0.65,Every 30 min,Per lot,Auto,Auto,ver tabela,ver tabela,Operator,Adjust Ink/Pressure
3,Screen Printing,Production,Color,Minor,Attribute,ΔE ≤ 1.5 vs standard,Colorimeter,Colorimeter,ISO 2859-1,II,1.50,Every 30 min,Per lot,Auto,Auto,ver tabela,ver tabela,Quality,Adjust Ink Formula
4,Screen Printing,Production,Smudge,Minor,Attribute,Absent,Visual,D65 Light Booth,ISO 2859-1,II,1.50,Continuous,Per lot,Auto,Auto,ver tabela,ver tabela,Operator,Adjust Speed
5,Screen Printing,Production,Pinholes,Minor,Attribute,Absent,Visual,Lupa 10x,ISO 2859-1,II,1.50,Continuous,Per lot,Auto,Auto,ver tabela,ver tabela,Operator,Clean Screen
6,Screen Printing,Production,Adhesion,Critical,Attribute,Class ≥ 4B (ASTM D3359),Cross Hatch,ASTM D3359 Kit,ISO 2859-1,II,0.10,Per lot,3 samples,—,3,0,1,Laboratory,Block Lot
7,Screen Printing,Production,Cure,Critical,Attribute,No removal after 50 rubs,MEK Rub Test,MEK Rub Test,ISO 2859-1,II,0.10,Per lot,3 samples,—,3,0,1,Laboratory,Reprocess (UV Re-cure)

## 4. Problems found -- summary

*"The data arrives like this -- raw. Look at the problems:"*

Running the three commands above on every table surfaces the same handful
of recurring, realistic data-entry problems:

- **Missing values** -- e.g. a handful of blank `OperatorId` / `MaintenanceTechnician`
  entries where a shift report wasn't fully filled in.
- **Inconsistent categories** -- the same process typed multiple ways in
  the same column: `Injection Molding`, `injection molding`,
  `INJECTION MOLDING`, `  Injection Molding  ` (stray whitespace). A naive
  `GROUP BY Process` would currently split what is really *one* process
  into several phantom categories.
- **Negative quantities** -- a small number of `RejectedQty` (rejected
  pieces) and `EndWeightKg` (remaining material weight) values are
  negative. Physically impossible: nobody rejects "-12" caps. This is a
  sign-entry error, most likely a scrap sheet transcribed with a stray
  minus sign.
- **Duplicated rows** -- a small fraction of fully identical rows exist in
  every fact table, consistent with a double MES submission or a re-run
  export job that appended instead of overwriting.
- **Placeholder nulls disguised as text** -- some text fields contain a
  single space, a dash (`-`, `--`, `---`), or a slash (`/`, `//`) where an
  operator meant "nothing to report" instead of leaving the cell empty.
  These are *not* legitimate categories and must not be treated as such
  (e.g. they must not show up as a phantom `"-"` maintenance technician in
  a report).

None of this is fixed here -- see `02_data_cleaning_production.ipynb` for
the cleaning strategy and the reasoning behind each choice.